import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

import {
  buildAccountRecoveryEvidence,
  evaluateAccountRecoveryCoverage,
  evaluateExactShaChecks,
} from '../../scripts/enterprise/build-account-recovery-evidence.mjs';

const SHA = 'a'.repeat(40);

function repositorySources() {
  return {
    route: readFileSync('src/app/api/auth/recovery/route.ts', 'utf8'),
    requestPage: readFileSync('src/app/[locale]/recuperar-senha/page.tsx', 'utf8'),
    resetPage: readFileSync('src/app/[locale]/reset-password/page.tsx', 'utf8'),
    login: readFileSync('src/app/[locale]/login/page.tsx', 'utf8'),
    middleware: readFileSync('src/middleware.ts', 'utf8'),
    authGate: readFileSync('src/components/auth/AuthProviderGate.tsx', 'utf8'),
    browserClient: readFileSync('src/integrations/supabase/client.ts', 'utf8'),
    routeTest: readFileSync('src/app/api/auth/recovery/route.test.ts', 'utf8'),
    e2eTest: readFileSync('tests/e2e/account-recovery.spec.ts', 'utf8'),
  };
}

function exactChecks() {
  return {
    evidenceComplete: true,
    exactSha: true,
    fullSecuritySuite: true,
    requiredChecks: true,
  };
}

function passingEvidence(overrides: Record<string, unknown> = {}) {
  const coverage = evaluateAccountRecoveryCoverage(repositorySources());
  return buildAccountRecoveryEvidence({
    coverage,
    exactChecks: exactChecks(),
    repository: 'renanescola40-afk/eurocomply_saas',
    branch: 'agent/account-recovery-enterprise-proof',
    targetSha: SHA,
    observedSha: SHA,
    runId: '123456',
    githubActions: true,
    sourceDigests: { route: 'b'.repeat(64) },
    generatedAt: '2026-07-17T00:00:00.000Z',
    ...overrides,
  });
}

describe('account recovery exact-SHA evidence', () => {
  it('requires the complete secure request and reset journey', () => {
    const coverage = evaluateAccountRecoveryCoverage(repositorySources());

    expect(coverage.complete).toBe(true);
    expect(coverage.checks).toEqual({
      secureRequestRoute: true,
      enumerationSafe: true,
      requestUx: true,
      resetCompletion: true,
      routeExposure: true,
      loginEntrypoint: true,
      safeUnconfiguredClient: true,
      routeTests: true,
      browserTests: true,
    });
  });

  it('promotes the control only for trusted exact-SHA execution', () => {
    const evidence = passingEvidence();

    expect(evidence.status).toBe('Complete');
    expect(evidence.outcome).toBe('passed');
    expect(evidence.controlsVerified).toEqual(['Account recovery validated']);
    expect(evidence.failures).toEqual([]);
    expect(evidence.evidenceIntegrity).toMatchObject({
      containsSensitiveValues: false,
      emailAddressesStored: false,
      recoveryTokensStored: false,
      passwordsStored: false,
      providerPayloadsStored: false,
      exactShaBound: true,
    });
  });

  it('fails closed for SHA mismatch or non-GitHub provenance', () => {
    const stale = passingEvidence({ observedSha: 'b'.repeat(40) });
    const local = passingEvidence({ githubActions: false });

    expect(stale.status).toBe('Open');
    expect(stale.controlsVerified).toEqual([]);
    expect(stale.failures).toContain('checked-out SHA must equal targetSha');
    expect(local.status).toBe('Open');
    expect(local.failures).toContain('evidence must be generated by GitHub Actions');
  });

  it('does not accept incomplete GitHub check evidence', () => {
    const result = evaluateExactShaChecks(
      {
        status: 'Complete',
        outcome: 'passed',
        targetSha: SHA,
        checks: [
          { name: 'fullSecuritySuite', status: 'PASS' },
          { name: 'requiredChecks', status: 'NOT_VERIFIED' },
        ],
      },
      SHA,
    );

    expect(result).toEqual({
      evidenceComplete: true,
      exactSha: true,
      fullSecuritySuite: true,
      requiredChecks: false,
    });
  });

  it('records an explicit provider and production evidence boundary', () => {
    const evidence = passingEvidence();

    expect(evidence.evidenceBoundary).toContain('does not prove production email delivery');
    expect(evidence.evidenceBoundary).toContain('Supabase provider availability');
    expect(JSON.stringify(evidence)).not.toContain('synthetic-recovery@example.test');
  });
});
