import { describe, expect, it } from 'vitest';
import {
  buildEvidence,
  evaluateLoggingAlerting,
} from '../../scripts/enterprise/build-centralized-logging-alert-evidence.mjs';

const SHA = 'a'.repeat(40);

const loggerSource = `
export const REDACTED_VALUE = '[redacted]';
export const STANDARD_SECURITY_EVENTS = ['rls_validation_failed','audit_chain_invalid','webhook_failed'];
const SENSITIVE_KEY_PATTERN = /token/;
const SENSITIVE_VALUE_PATTERNS = [];
JSON.stringify({ timestamp: '', requestId: '', event: '' });
Sentry.withScope(() => {});
Sentry.captureMessage('security');
const alert_severity = 'critical';
const security_event = 'rls_validation_failed';
`;

const alertingRunbook = `
SEV-1 SEV-2 Threshold Customer communication
Primary owner Backup owner
Release is **No-Go**
Evidence to capture
Deployment SHA
Closure criteria
`;

const loggingRunbook = `Use Vercel, Supabase logs and Sentry for production observability.`;

describe('centralized logging and alert evidence', () => {
  it('validates structured logging and alert routing contracts', () => {
    const evaluation = evaluateLoggingAlerting({ loggerSource, alertingRunbook, loggingRunbook });
    expect(evaluation.centralizedLogging).toBe(true);
    expect(evaluation.alertRouting).toBe(true);
  });

  it('produces Complete evidence only with exact-SHA GitHub provenance', () => {
    const evaluation = evaluateLoggingAlerting({ loggerSource, alertingRunbook, loggingRunbook });
    const evidence = buildEvidence({
      evaluation,
      repository: 'renanescola40-afk/eurocomply_saas',
      branch: 'agent/example',
      targetSha: SHA,
      observedSha: SHA,
      runId: '123',
      githubActions: true,
      sourceDigests: { logger: 'b'.repeat(64), alertingRunbook: 'c'.repeat(64), loggingRunbook: 'd'.repeat(64) },
    });

    expect(evidence.status).toBe('Complete');
    expect(evidence.checks.centralizedLogging).toBe(true);
    expect(evidence.checks.alertRouting).toBe(true);
    expect(evidence.controlsVerified).toEqual([
      'Centralized logging validated',
      'Alert routing validated',
    ]);
    expect(evidence.evidenceIntegrity.containsSensitiveValues).toBe(false);
  });

  it('fails closed for missing routing or mismatched provenance', () => {
    const evaluation = evaluateLoggingAlerting({
      loggerSource: loggerSource.replace('Sentry.captureMessage', 'captureDisabled'),
      alertingRunbook,
      loggingRunbook,
    });
    const evidence = buildEvidence({
      evaluation,
      repository: 'renanescola40-afk/eurocomply_saas',
      branch: 'agent/example',
      targetSha: SHA,
      observedSha: 'f'.repeat(40),
      runId: '',
      githubActions: false,
      sourceDigests: {},
    });

    expect(evidence.status).toBe('Open');
    expect(evidence.controlsVerified).toEqual([]);
    expect(evidence.checks.alertRouting).toBe(false);
    expect(evidence.failures).toEqual(expect.arrayContaining([
      'evidence must be generated by GitHub Actions',
      'checked-out SHA must equal targetSha',
      'runId must be numeric',
    ]));
  });
});
