import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

import {
  buildProviderFailureEvidence,
  evaluateExactShaChecks,
  evaluateProviderFailureCoverage,
} from '../../scripts/enterprise/build-provider-failure-evidence.mjs';

const SHA = 'a'.repeat(40);

function repositorySources() {
  return {
    taxonomy: readFileSync('src/server/providers/failure.ts', 'utf8'),
    apiGuards: readFileSync('src/server/security/api-guards.ts', 'utf8'),
    checkout: readFileSync('src/app/api/billing/checkout/route.ts', 'utf8'),
    portal: readFileSync('src/app/api/billing/portal/route.ts', 'utf8'),
    email: readFileSync('src/lib/email/server-sender.ts', 'utf8'),
    recovery: readFileSync('src/app/api/auth/recovery/route.ts', 'utf8'),
    taxonomyTest: readFileSync('tests/security/provider-failure-classification.test.ts', 'utf8'),
    recoveryTest: readFileSync('src/app/api/auth/recovery/route.test.ts', 'utf8'),
  };
}

function exactChecks() {
  return {
    evidenceComplete: true,
    exactSha: true,
    fullSecuritySuite: true,
    requiredChecks: true,
  };
}

function passingEvidence(overrides: Record<string, unknown> = {}) {
  return buildProviderFailureEvidence({
    coverage: evaluateProviderFailureCoverage(repositorySources()),
    exactChecks: exactChecks(),
    repository: 'renanescola40-afk/eurocomply_saas',
    branch: 'agent/provider-failure-taxonomy-proof',
    targetSha: SHA,
    observedSha: SHA,
    runId: '123456',
    githubActions: true,
    sourceDigests: { taxonomy: 'b'.repeat(64) },
    generatedAt: '2026-07-17T00:00:00.000Z',
    ...overrides,
  });
}

describe('provider failure exact-SHA evidence', () => {
  it('requires central classification and real provider boundary integration', () => {
    const coverage = evaluateProviderFailureCoverage(repositorySources());

    expect(coverage.complete).toBe(true);
    expect(coverage.checks).toEqual({
      centralTaxonomy: true,
      safeApiContract: true,
      stripeIntegration: true,
      resendIntegration: true,
      supabaseIntegration: true,
      classificationTests: true,
    });
  });

  it('promotes only trusted exact-SHA execution', () => {
    const evidence = passingEvidence();

    expect(evidence.status).toBe('Complete');
    expect(evidence.outcome).toBe('passed');
    expect(evidence.controlsVerified).toEqual(['Provider failures are distinguishable']);
    expect(evidence.failures).toEqual([]);
    expect(evidence.evidenceIntegrity).toEqual({
      containsSensitiveValues: false,
      rawProviderMessagesStored: false,
      rawProviderPayloadsStored: false,
      credentialsStored: false,
      customerDataStored: false,
      exactShaBound: true,
    });
  });

  it('fails closed for stale checkout, local provenance or incomplete required checks', () => {
    const stale = passingEvidence({ observedSha: 'b'.repeat(40) });
    const local = passingEvidence({ githubActions: false });
    const incomplete = passingEvidence({
      exactChecks: { ...exactChecks(), requiredChecks: false },
    });

    expect(stale.status).toBe('Open');
    expect(stale.controlsVerified).toEqual([]);
    expect(stale.failures).toContain('checked-out SHA must equal targetSha');
    expect(local.status).toBe('Open');
    expect(local.failures).toContain('evidence must be generated by GitHub Actions');
    expect(incomplete.status).toBe('Open');
    expect(incomplete.failures).toContain('required exact-SHA execution evidence is incomplete');
  });

  it('does not accept a partial GitHub check document', () => {
    expect(
      evaluateExactShaChecks(
        {
          status: 'Complete',
          outcome: 'passed',
          targetSha: SHA,
          checks: [
            { name: 'fullSecuritySuite', status: 'PASS' },
            { name: 'requiredChecks', status: 'NOT_VERIFIED' },
          ],
        },
        SHA,
      ),
    ).toEqual({
      evidenceComplete: true,
      exactSha: true,
      fullSecuritySuite: true,
      requiredChecks: false,
    });
  });

  it('records the production and provider evidence boundary explicitly', () => {
    const evidence = passingEvidence();

    expect(evidence.evidenceBoundary).toContain('does not prove a real production provider outage');
    expect(evidence.evidenceBoundary).toContain('provider availability');
    expect(evidence.evidenceBoundary).toContain('alert delivery');
    expect(JSON.stringify(evidence)).not.toContain('sk_live_');
    expect(JSON.stringify(evidence)).not.toContain('Bearer ');
  });
});
