import { PublicLegalReviewPage } from '@/components/legal/public-legal-review-page';
import { isSupportedLocale, type Locale } from '@/lib/i18n/locales';

const LAST_UPDATED = '9 September 2026';

const copy: Record<Locale, { eyebrow: string; title: string; summary: string; sections: Array<{ title: string; paragraphs?: string[]; items?: string[] }> }> = {
  en: {
    eyebrow: 'International Data Transfers',
    title: 'Transfer mechanisms and provider verification',
    summary: 'This review draft records the technical transfer boundary without claiming that any SCC, DPA or other contractual mechanism has been executed unless attributable evidence exists.',
    sections: [
      { title: 'Production and operational providers in scope', items: ['Vercel may process application traffic, deployment metadata and operational logs. The canonical public site is serving, but the observed Production deployment is older than the protected-main release; exact-current-main binding remains open.', 'Supabase provides database, authentication and storage services. The Production project is evidenced in eu-west-1 and the selected V41 migration inventory is live 13/13; governed promotion provenance remains open.', 'Stripe processes billing identifiers and payment metadata when billing is enabled. The canonical LIVE control plane is active, but legitimate LIVE subscription authority is currently 0 under the exact evidence contract.', 'Google OAuth / Google Identity runtime integration is implemented; final legal role, applicable contract/DPA, region, retention and transfer treatment remain under review.', 'Google Workspace corporate mail is operational; earlier account-specific plan/EMEA evidence is retained while current agreement/CDPA, region, retention and transfer facts remain evidence-required.', 'GitHub Actions supports CI/CD and protected recovery/security workflows and can transiently process Production database data on GitHub-hosted runners; applicable account DPA/transfer treatment remains under review.', 'Earlier direct Sentry Production release-binding evidence is historical; current protected exact-release producer acceptance and account-specific contractual/location facts remain open.', 'PostHog Production source/configuration has historically targeted EU endpoints, but the connected assurance project is not the Production project; account-specific facts remain under verification.', 'The Upstash Redis-backed integration remains implemented. Earlier direct Production proof is historical; current protected provider/runtime acceptance and account plan, region, retention and DPA/transfer treatment remain open.'] },
      { title: 'Known location evidence', paragraphs: ['The Production Supabase project is evidenced in eu-west-1. Historical PostHog configuration targeted EU endpoints, but the actual Production account/project still requires attribution. Google Workspace EMEA billing evidence is not a processing/storage region. Remaining account-specific locations and onward transfers require applicable evidence before final approval.'] },
      { title: 'Transfer mechanism gate', items: ['Do not claim executed Standard Contractual Clauses without applicable contract evidence.', 'Do not infer a provider DPA, transfer mechanism, retention period or processing country from source code, runtime presence or billing entity alone.', 'Do not convert historical/direct runtime binding or protected producer evidence into contractual acceptance.', 'Reconcile provider purpose, data categories, location/region, transfer mechanism, DPA status and evidence date before final approval.'] },
      { title: 'Customer contracting', paragraphs: ['The final DPA and transfer annex must match the actual Production and operational data flow and counsel-approved provider/subprocessor register. Any required SCC module, UK addendum or other transfer safeguard remains a qualified legal and contracting decision.'] },
    ],
  },
  pt: {
    eyebrow: 'Transferências Internacionais de Dados',
    title: 'Mecanismos de transferência e verificação de fornecedores',
    summary: 'Este rascunho regista o limite técnico de transferências sem afirmar que SCC, DPA ou outro mecanismo contratual foi celebrado quando não existe evidência atribuível.',
    sections: [
      { title: 'Fornecedores de Production e operacionais em escopo', items: ['A Vercel pode tratar tráfego da aplicação, metadados de deployment e logs operacionais. O site público está a servir, mas o deployment Production observado é anterior ao release protegido em main; o binding exact-current-main permanece aberto.', 'A Supabase fornece base de dados, autenticação e storage. O projeto Production está evidenciado em eu-west-1 e o inventário V41 selecionado está live 13/13; a proveniência da promoção governada permanece aberta.', 'A Stripe trata identificadores de billing e metadados de pagamento quando billing está ativo. O control plane LIVE está ativo, mas a autoridade legítima de subscrição LIVE observada é 0 segundo o contrato exato de evidência.', 'Google OAuth / Google Identity tem integração de runtime implementada; função jurídica final, contrato/DPA, região, retenção e transferências permanecem em revisão.', 'O correio corporativo Google Workspace está operacional; evidência anterior de plano/entidade EMEA é retida, enquanto acordo/CDPA, região, retenção e transferências atuais permanecem dependentes de evidência.', 'GitHub Actions suporta CI/CD e workflows protegidos de recovery/security e pode tratar transitoriamente dados da base Production em runners hospedados pelo GitHub; DPA/transferências aplicáveis permanecem em revisão.', 'A evidência direta anterior de binding de release Production no Sentry é histórica; aceitação atual do producer protegido e factos contratuais/de localização da conta permanecem abertos.', 'Source/configuration de Production do PostHog historicamente apontou para endpoints UE, mas o projeto assurance conectado não é o projeto de Production; factos da conta permanecem em verificação.', 'A integração Redis-backed da Upstash permanece implementada. A prova direta anterior em Production é histórica; aceitação protegida atual e plano, região, retenção e DPA/transferências permanecem abertos.'] },
      { title: 'Evidência conhecida de localização', paragraphs: ['O projeto Supabase de Production está evidenciado em eu-west-1. A configuração histórica do PostHog apontou para endpoints UE, mas a conta/projeto real de Production ainda requer atribuição. Evidência EMEA do Google Workspace não equivale a uma região de armazenamento/tratamento. As restantes localizações e transferências específicas da conta exigem evidência aplicável antes da aprovação final.'] },
      { title: 'Gate do mecanismo de transferência', items: ['Não afirmar SCC celebradas sem evidência contratual aplicável.', 'Não inferir DPA, mecanismo de transferência, conservação ou país de tratamento apenas a partir do código, runtime ou entidade de faturação.', 'Não converter binding histórico/direto de runtime ou evidência de producer protegido em aceitação contratual.', 'Reconciliar finalidade, categorias de dados, localização/região, mecanismo de transferência, estado do DPA e data da evidência antes da aprovação final.'] },
      { title: 'Contratação com clientes', paragraphs: ['O DPA final e o anexo de transferências devem corresponder aos fluxos de dados de Production e ao registo de providers/subprocessadores aprovado por counsel. Qualquer módulo SCC, adenda UK ou outra salvaguarda permanece decisão jurídica e contratual qualificada.'] },
    ],
  },
  es: {
    eyebrow: 'Transferencias Internacionales de Datos', title: 'Mecanismos de transferencia y verificación de proveedores', summary: 'Borrador técnico que no afirma SCC, DPA u otros mecanismos sin evidencia atribuible.', sections: [
      { title: 'Proveedores', items: ['Vercel sirve el sitio público pero el deployment Production observado es anterior a protected main. Supabase está en eu-west-1 con V41 13/13 live y procedencia gobernada aún abierta. Stripe LIVE está activo pero la autoridad legítima de suscripción observada es 0. Google OAuth y Google Workspace tienen integración/uso operativo con hechos legales pendientes. GitHub Actions puede procesar transitoriamente datos de la base Production en runners alojados por GitHub. Las pruebas directas anteriores de Sentry y Upstash son históricas hasta nueva aceptación protegida. PostHog históricamente apuntó a endpoints UE, pero el proyecto assurance conectado no es Production.'] },
      { title: 'Verificación', paragraphs: ['Regiones, transferencias ulteriores, DPA, SCC, retención y hechos específicos de cuenta deben verificarse antes de aprobación final.'] },
      { title: 'Límite de evidencia', items: ['No inferir mecanismos contractuales desde código, runtime o facturación.', 'No convertir evidencia histórica o binding runtime en aceptación contractual.', 'No afirmar SCC ejecutadas sin evidencia aplicable.'] },
    ],
  },
  fr: {
    eyebrow: 'Transferts Internationaux de Données', title: 'Mécanismes de transfert et vérification des fournisseurs', summary: 'Projet technique ne revendiquant aucune SCC, DPA ou garantie contractuelle sans preuve attribuable.', sections: [
      { title: 'Fournisseurs', items: ['Vercel sert le site public mais le deployment Production observé est antérieur au protected main. Supabase est en eu-west-1 avec V41 13/13 live et provenance gouvernée encore ouverte. Stripe LIVE est actif mais l’autorité de souscription légitime observée est 0. Google OAuth et Google Workspace ont une intégration/utilisation opérationnelle avec des faits juridiques ouverts. GitHub Actions peut traiter temporairement des données de la base Production sur des runners hébergés par GitHub. Les preuves directes antérieures Sentry et Upstash sont historiques jusqu’à une nouvelle acceptation protégée. PostHog a historiquement ciblé des endpoints UE mais le projet assurance connecté n’est pas Production.'] },
      { title: 'Vérification', paragraphs: ['Régions, transferts, DPA, SCC, conservation et faits spécifiques au compte doivent être vérifiés avant validation finale.'] },
      { title: 'Limite de preuve', items: ['Ne pas déduire de mécanisme contractuel du code, runtime ou facturation.', 'Ne pas convertir une preuve historique ou un binding runtime en acceptation contractuelle.', 'Ne pas déclarer de SCC conclues sans preuve applicable.'] },
    ],
  },
  it: {
    eyebrow: 'Trasferimenti Internazionali di Dati', title: 'Meccanismi di trasferimento e verifica dei fornitori', summary: 'Bozza tecnica che non dichiara SCC, DPA o altre garanzie contrattuali senza evidenza attribuibile.', sections: [
      { title: 'Fornitori', items: ['Vercel serve il sito pubblico ma il deployment Production osservato è precedente al protected main. Supabase è in eu-west-1 con V41 13/13 live e provenienza governata ancora aperta. Stripe LIVE è attivo ma l’autorità di sottoscrizione legittima osservata è 0. Google OAuth e Google Workspace hanno integrazione/uso operativo con fatti legali aperti. GitHub Actions può trattare temporaneamente dati del database Production su runner ospitati da GitHub. Le precedenti prove dirette di Sentry e Upstash sono storiche fino a nuova accettazione protetta. PostHog ha storicamente usato endpoint UE ma il progetto assurance collegato non è Production.'] },
      { title: 'Verifica', paragraphs: ['Regioni, trasferimenti, DPA, SCC, conservazione e fatti specifici dell’account devono essere verificati prima dell’approvazione finale.'] },
      { title: 'Limite delle evidenze', items: ['Non dedurre meccanismi contrattuali dal codice, runtime o fatturazione.', 'Non convertire evidenze storiche o binding runtime in accettazione contrattuale.', 'Non dichiarare SCC sottoscritte senza evidenza applicabile.'] },
    ],
  },
  de: {
    eyebrow: 'Internationale Datentransfers', title: 'Transfermechanismen und Anbieterprüfung', summary: 'Technischer Entwurf ohne Behauptung von SCC, DPA oder Vertragsmechanismen ohne zurechenbare Nachweise.', sections: [
      { title: 'Anbieter', items: ['Vercel liefert die öffentliche Seite aus, aber das beobachtete Production-Deployment liegt hinter protected main. Supabase ist in eu-west-1 mit V41 13/13 live; die Governance-Provenienz bleibt offen. Stripe LIVE ist aktiv, aber die beobachtete legitime Subscription-Autorität ist 0. Google OAuth und Google Workspace haben Integration/operative Nutzung mit offenen Rechtsfakten. GitHub Actions kann Production-Datenbankdaten vorübergehend auf von GitHub gehosteten Runnern verarbeiten. Frühere direkte Sentry- und Upstash-Nachweise sind historisch bis zu einer neuen geschützten Akzeptanz. PostHog zielte historisch auf EU-Endpunkte, aber das verbundene Assurance-Projekt ist nicht Production.'] },
      { title: 'Prüfung', paragraphs: ['Regionen, Transfers, DPA, SCC, Aufbewahrung und kontospezifische Fakten müssen vor finaler Freigabe geprüft werden.'] },
      { title: 'Nachweisgrenze', items: ['Keine Vertragsmechanismen aus Code, Runtime oder Abrechnung ableiten.', 'Historische Nachweise oder Runtime-Binding nicht in Vertragsakzeptanz umdeuten.', 'Keine abgeschlossenen SCC ohne anwendbaren Nachweis behaupten.'] },
    ],
  },
};

export default async function TransfersPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale: rawLocale } = await params;
  const locale: Locale = isSupportedLocale(rawLocale) ? rawLocale : 'en';
  const page = copy[locale];

  return <PublicLegalReviewPage locale={locale} eyebrow={page.eyebrow} title={page.title} summary={page.summary} documentId="international-data-transfers" version="0.1-review" lastUpdated={LAST_UPDATED} sections={page.sections} />;
}
