import { PublicLegalReviewPage } from '@/components/legal/public-legal-review-page';
import { isSupportedLocale, type Locale } from '@/lib/i18n/locales';

const LAST_UPDATED = '24 August 2026';

const copy: Record<Locale, { eyebrow: string; title: string; summary: string; sections: Array<{ title: string; paragraphs?: string[]; items?: string[] }> }> = {
  en: {
    eyebrow: 'International Data Transfers',
    title: 'Transfer mechanisms and provider verification',
    summary: 'This review draft records the technical transfer boundary without claiming that any SCC, DPA or other contractual mechanism has been executed unless independent evidence exists.',
    sections: [
      { title: 'Production and operational providers in scope', items: ['Vercel may process application traffic, deployment metadata and operational logs depending on configuration.', 'Supabase provides database, authentication and storage services for the configured project.', 'Stripe processes billing identifiers and payment metadata when billing is enabled.', 'Google OAuth / Google Identity is used for optional Production authentication and may process authentication identifiers and provider-returned profile metadata; its final legal role, applicable contract/DPA, region, retention and transfer treatment remain under review.', 'Google Workspace is actively used for RISCK COMPLY corporate support, security, procurement and legal communications. Account-specific evidence proves Business Starter for risckcomply.com and Google Cloud EMEA Limited as the billed EMEA entity; exact account CDPA incorporation, region, retention and onward-transfer treatment remain under review.', 'GitHub Actions supports CI/CD and protected recovery/security workflows; protected recovery can transiently process Production database data on hosted runners, while the applicable company-account DPA/transfer treatment remains unproven.', 'Sentry processes diagnostic/error-monitoring metadata when the integration is active.', 'PostHog is present in the Production analytics integration, but the currently connected assurance project does not match the Production project; account-specific facts remain under verification.', 'Upstash Redis is materially required by the fail-closed distributed rate-limit/security architecture and predecessor binding evidence exists; the retained exact-current observation did not reach the Redis-backed path, so exact-current runtime reproof remains open together with account plan, region, retention and DPA/transfer treatment.'] },
      { title: 'Known location evidence', paragraphs: ['The connected Production Supabase project is evidenced in eu-west-1. The Production PostHog client uses EU service endpoints, but the actual Production project/account still requires attribution. Google Workspace billing identifies Google Cloud EMEA Limited as the account billing entity, but that is not presented as a data-processing/storage region. Google OAuth, Workspace, GitHub Actions, Upstash and the remaining provider processing locations/onward transfers must be verified from applicable account and contractual evidence before final approval.'] },
      { title: 'Transfer mechanism gate', items: ['Do not claim executed Standard Contractual Clauses without the applicable signed or provider-contract evidence.', 'Do not infer a provider DPA, transfer mechanism, retention period or processing country from source code, runtime presence or billing entity alone.', 'Do not promote historical or architecture evidence into an exact-current runtime claim without a retained attributable observation.', 'Reconcile provider purpose, data categories, location/region, transfer, transfer mechanism, DPA status and evidence date before final approval.'] },
      { title: 'Customer contracting', paragraphs: ['The final DPA and transfer annex must match the actual Production and operational data flow and counsel-approved provider/subprocessor register. Any required SCC module, UK addendum or other transfer safeguard remains a qualified legal and contracting decision.'] },
    ],
  },
  pt: {
    eyebrow: 'Transferências Internacionais de Dados',
    title: 'Mecanismos de transferência e verificação de fornecedores',
    summary: 'Este rascunho regista o limite técnico de transferências sem afirmar que SCC, DPA ou outro mecanismo contratual foi celebrado quando não existe evidência independente.',
    sections: [
      { title: 'Fornecedores de Production e operacionais em escopo', items: ['A Vercel pode tratar tráfego da aplicação, metadados de deployment e logs operacionais conforme a configuração.', 'A Supabase fornece base de dados, autenticação e storage para o projeto configurado.', 'A Stripe trata identificadores de billing e metadados de pagamento quando billing está ativo.', 'Google OAuth / Google Identity é usado para autenticação opcional em Production e pode tratar identificadores de autenticação e metadados de perfil devolvidos pelo provider; função jurídica final, contrato/DPA aplicável, região, retenção e transferências permanecem em revisão.', 'Google Workspace é usado ativamente nas comunicações corporativas de suporte, segurança, procurement e jurídico da RISCK COMPLY. Evidência específica da conta prova Business Starter para risckcomply.com e Google Cloud EMEA Limited como entidade EMEA faturada; incorporação do CDPA da conta, região, retenção e transferências posteriores permanecem em revisão.', 'GitHub Actions suporta CI/CD e workflows protegidos de recovery/segurança; o recovery protegido pode tratar transitoriamente dados da base Production em runners hospedados, enquanto DPA/transferências aplicáveis à conta empresarial permanecem não provados.', 'A Sentry trata metadados de diagnóstico e error monitoring quando a integração está ativa.', 'A integração PostHog está presente em Production, mas o projeto atualmente ligado para assurance não corresponde ao projeto de Production; os factos da conta permanecem em verificação.', 'A Upstash Redis é materialmente necessária à arquitetura fail-closed de rate limiting/controlos de segurança e existe evidência de binding anterior; a observação exact-current retida não alcançou o caminho Redis, portanto a revalidação exact-current permanece aberta, juntamente com plano, região, retenção e DPA/transferências da conta.'] },
      { title: 'Evidência conhecida de localização', paragraphs: ['O projeto Supabase de Production está evidenciado em eu-west-1. O cliente PostHog de Production usa endpoints de serviço da UE, mas o projeto/conta real de Production ainda requer atribuição. A faturação Google Workspace identifica Google Cloud EMEA Limited como entidade de faturação da conta, mas isso não é apresentado como região de armazenamento/tratamento. Google OAuth, Workspace, GitHub Actions, Upstash e as restantes localizações/transferências posteriores devem ser verificadas através de evidência aplicável da conta e contratual antes da aprovação final.'] },
      { title: 'Gate do mecanismo de transferência', items: ['Não afirmar SCC celebradas sem evidência contratual aplicável.', 'Não inferir DPA, mecanismo de transferência, conservação ou país de tratamento apenas a partir do código, presença técnica em runtime ou entidade de faturação.', 'Não promover evidência histórica ou de arquitetura para uma alegação exact-current sem observação atribuível retida.', 'Reconciliar finalidade, categorias de dados, localização/região, transferência, mecanismo, estado do DPA e data da evidência antes da aprovação final.'] },
      { title: 'Contratação com clientes', paragraphs: ['O DPA final e o anexo de transferências devem corresponder aos fluxos de dados de Production e operacionais e ao registo de providers/subprocessadores aprovado por counsel. Qualquer módulo SCC, adenda UK ou outra salvaguarda permanece decisão jurídica e contratual qualificada.'] },
    ],
  },
  es: {
    eyebrow: 'Transferencias Internacionales de Datos', title: 'Mecanismos de transferencia y verificación de proveedores', summary: 'Borrador técnico que no afirma SCC, DPA u otros mecanismos sin evidencia independiente.', sections: [
      { title: 'Proveedores', items: ['Vercel, Supabase, Stripe y Sentry están dentro del perímetro técnico según sus funciones activas. Google OAuth / Google Identity se usa para autenticación opcional en Production. Google Workspace se usa para comunicaciones corporativas de soporte, seguridad, procurement y legal; la cuenta Business Starter y la entidad de facturación EMEA están probadas, pero CDPA, región, retención y transferencias específicas de la cuenta siguen en revisión. GitHub Actions soporta CI/CD y workflows protegidos de recuperación/seguridad y puede procesar datos Production transitoriamente. PostHog está presente en Production, pero el proyecto conectado para assurance no coincide con el proyecto de Production. Upstash Redis es material para la arquitectura de seguridad; existe evidencia histórica, pero la revalidación exact-current retenida sigue abierta.'] },
      { title: 'Verificación', paragraphs: ['Las regiones, transferencias ulteriores, DPA, SCC y retención de Google OAuth, Google Workspace, GitHub Actions, Upstash y demás proveedores deben verificarse en las cuentas y contratos aplicables antes de aprobación final.'] },
      { title: 'Límite de evidencia', items: ['No inferir un mecanismo contractual desde el código, la presencia runtime o una entidad de facturación.', 'No promover evidencia histórica a una afirmación exact-current sin observación atribuible retenida.', 'No afirmar SCC ejecutadas sin evidencia aplicable.'] },
    ],
  },
  fr: {
    eyebrow: 'Transferts Internationaux de Données', title: 'Mécanismes de transfert et vérification des fournisseurs', summary: 'Projet technique ne revendiquant aucune SCC, DPA ou autre garantie contractuelle sans preuve indépendante.', sections: [
      { title: 'Fournisseurs', items: ['Vercel, Supabase, Stripe et Sentry sont dans le périmètre technique selon les services actifs. Google OAuth / Google Identity est utilisé pour l’authentification optionnelle Production. Google Workspace est utilisé pour les communications d’entreprise de support, sécurité, procurement et juridique ; le compte Business Starter et l’entité de facturation EMEA sont prouvés, mais le CDPA, la région, la rétention et les transferts propres au compte restent à examiner. GitHub Actions prend en charge CI/CD et des workflows protégés de reprise/sécurité. PostHog est présent en Production, mais le projet connecté pour assurance ne correspond pas au projet Production. Upstash Redis est matériel pour l’architecture de sécurité ; des preuves historiques existent mais la revalidation exacte actuelle conservée reste ouverte.'] },
      { title: 'Vérification', paragraphs: ['Les régions, transferts ultérieurs, DPA, SCC et durées de conservation de Google OAuth, Google Workspace, GitHub Actions, Upstash et des autres fournisseurs doivent être vérifiés dans les comptes et contrats applicables avant validation finale.'] },
      { title: 'Limite de preuve', items: ['Ne pas déduire un mécanisme contractuel du code source, de la seule présence runtime ou d’une entité de facturation.', 'Ne pas promouvoir une preuve historique en affirmation exacte actuelle sans observation attribuable conservée.', 'Ne pas déclarer de SCC conclues sans preuve applicable.'] },
    ],
  },
  it: {
    eyebrow: 'Trasferimenti Internazionali di Dati', title: 'Meccanismi di trasferimento e verifica dei fornitori', summary: 'Bozza tecnica che non dichiara SCC, DPA o altre garanzie contrattuali senza evidenza indipendente.', sections: [
      { title: 'Fornitori', items: ['Vercel, Supabase, Stripe e Sentry rientrano nel perimetro tecnico secondo i servizi attivi. Google OAuth / Google Identity è usato per l’autenticazione opzionale Production. Google Workspace è usato per comunicazioni aziendali di supporto, sicurezza, procurement e legali; account Business Starter ed entità di fatturazione EMEA sono provati, mentre CDPA, regione, retention e trasferimenti specifici dell’account restano in revisione. GitHub Actions supporta CI/CD e workflow protetti di recovery/sicurezza. PostHog è presente in Production, ma il progetto assurance non corrisponde al progetto Production. Upstash Redis è materiale per l’architettura di sicurezza; esistono evidenze storiche ma la revalidazione exact-current conservata resta aperta.'] },
      { title: 'Verifica', paragraphs: ['Regioni, trasferimenti successivi, DPA, SCC e conservazione di Google OAuth, Google Workspace, GitHub Actions, Upstash e degli altri provider devono essere verificati negli account e contratti applicabili prima dell’approvazione finale.'] },
      { title: 'Limite delle evidenze', items: ['Non dedurre un meccanismo contrattuale dal codice, dalla sola presenza runtime o da un’entità di fatturazione.', 'Non promuovere evidenza storica a un’affermazione exact-current senza osservazione attribuibile conservata.', 'Non dichiarare SCC sottoscritte senza evidenza applicabile.'] },
    ],
  },
  de: {
    eyebrow: 'Internationale Datentransfers', title: 'Transfermechanismen und Anbieterprüfung', summary: 'Technischer Entwurf ohne Behauptung von SCC, DPA oder anderen Vertragsmechanismen ohne unabhängige Nachweise.', sections: [
      { title: 'Anbieter', items: ['Vercel, Supabase, Stripe und Sentry liegen entsprechend den aktiven Diensten im technischen Umfang. Google OAuth / Google Identity wird für optionale Production-Authentifizierung genutzt. Google Workspace wird für geschäftliche Support-, Sicherheits-, Procurement- und Rechtskommunikation genutzt; Business-Starter-Konto und EMEA-Abrechnungseinheit sind nachgewiesen, während kontospezifisches CDPA, Region, Aufbewahrung und Transfers offen bleiben. GitHub Actions unterstützt CI/CD und geschützte Recovery-/Security-Workflows. PostHog ist in Production vorhanden, aber das verbundene Assurance-Projekt entspricht nicht dem Production-Projekt. Upstash Redis ist für die Sicherheitsarchitektur wesentlich; historische Nachweise existieren, aber die aufbewahrte exakt aktuelle Revalidierung bleibt offen.'] },
      { title: 'Prüfung', paragraphs: ['Regionen, Weiterübermittlungen, DPA, SCC und Aufbewahrung für Google OAuth, Google Workspace, GitHub Actions, Upstash und weitere Anbieter müssen vor der finalen Freigabe in den anwendbaren Konten und Verträgen geprüft werden.'] },
      { title: 'Nachweisgrenze', items: ['Vertragliche Mechanismen nicht aus Quellcode, bloßer Runtime-Präsenz oder einer Abrechnungseinheit ableiten.', 'Historische Nachweise nicht ohne aufbewahrte zuordenbare Beobachtung zu einer exakt aktuellen Aussage hochstufen.', 'Keine abgeschlossenen SCC ohne anwendbaren Nachweis behaupten.'] },
    ],
  },
};

export default async function TransfersPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale: rawLocale } = await params;
  const locale: Locale = isSupportedLocale(rawLocale) ? rawLocale : 'en';
  const page = copy[locale];

  return <PublicLegalReviewPage locale={locale} eyebrow={page.eyebrow} title={page.title} summary={page.summary} documentId="international-data-transfers" version="0.1-review" lastUpdated={LAST_UPDATED} sections={page.sections} />;
}
