import { DOCUMENT_BUCKET, buildDocumentStoragePath } from '@/lib/documents/upload';
import { getComplianceTemplate } from '@/lib/compliance/templates';
import { reportError } from '@/lib/observability/report-error';
import { createAdminClient } from '@/lib/supabase/admin';
import { createDocument } from '@/server/actions/documents';

function templateToMarkdown(template: NonNullable<ReturnType<typeof getComplianceTemplate>>) {
  return [
    `# ${template.title}`,
    '',
    template.description,
    '',
    `Recommended owner: ${template.recommendedOwner}`,
    '',
    '## Sections',
    ...template.sections.map((section) => `- ${section}`),
    '',
    '---',
    'Generated by EuroComply template library.',
  ].join('\n');
}

export async function createDocumentFromTemplate(input: { organizationId: string; templateId: string }, userId: string) {
  const template = getComplianceTemplate(input.templateId);
  const context = { area: 'template_document', organizationId: input.organizationId, userId, templateId: input.templateId };

  if (!template) {
    const error = new Error('Compliance template not found');
    reportError(error, context);
    throw error;
  }

  const supabase = createAdminClient();
  const fileName = `${template.id}.md`;
  const content = templateToMarkdown(template);
  const storagePath = buildDocumentStoragePath({
    organizationId: input.organizationId,
    userId,
    fileName,
  });

  const { error: uploadError } = await supabase.storage.from(DOCUMENT_BUCKET).upload(storagePath, content, {
    contentType: 'text/markdown; charset=utf-8',
    upsert: false,
  });

  if (uploadError) {
    reportError(uploadError, context);
    throw uploadError;
  }

  try {
    return await createDocument(
      {
        organizationId: input.organizationId,
        name: template.title,
        category: template.category,
        storagePath,
        mimeType: 'text/markdown',
        sizeBytes: Buffer.byteLength(content, 'utf8'),
      },
      userId,
    );
  } catch (error) {
    reportError(error, context);
    await supabase.storage.from(DOCUMENT_BUCKET).remove([storagePath]);
    throw error;
  }
}
