import { locales, type Locale } from '@/lib/i18n/routing';

export type AddOnsCopy = {
  eyebrow: string;
  title: string;
  subtitle: string;
  currentPlan: string;
  planActive: string;
  activeAddOns: string;
  billingAuthority: string;
  billingAuthorityBody: string;
  included: string;
  active: string;
  available: string;
  unavailable: string;
  requiresPlan: (plan: string) => string;
  perMonth: string;
  perYear: string;
  includedWithEnterprise: string;
  availableOn: string;
  dependencies: string;
  catalogTitle: string;
  catalogSubtitle: string;
  viewPlans: string;
  reviewBilling: string;
  contactBillingAdmin: string;
  invalidPlan: string;
  selectedPlan: string;
  selectedPlanBody: string;
  selectedPlanPrice: string;
  continuePlanReview: string;
  backToPricing: string;
  focusLabel: string;
  noDirectPurchase: string;
  noDirectPurchaseBody: string;
  categories: Record<'compliance' | 'platform' | 'capacity' | 'branding', string>;
};

const copy: Record<Locale, AddOnsCopy> = {
  en: {
    eyebrow: 'Upgrade Center', title: 'Know exactly what your organization can use — and what unlocks next.', subtitle: 'This workspace reads the current organization plan and active add-ons from the billing authority. Nothing is unlocked by a URL, preview mode or browser state.', currentPlan: 'Current plan', planActive: 'Plan authority active', activeAddOns: 'Active add-ons', billingAuthority: 'Billing-confirmed access', billingAuthorityBody: 'Access changes only after the billing authority confirms the plan or add-on. This page never grants entitlements by itself.', included: 'Included', active: 'Active', available: 'Available', unavailable: 'Not available on this plan', requiresPlan: (plan) => `Requires ${plan} or higher`, perMonth: '/month', perYear: '/year', includedWithEnterprise: 'Included with Enterprise', availableOn: 'Available on', dependencies: 'Dependencies', catalogTitle: 'Available capability extensions', catalogSubtitle: 'Canonical prices and availability come from the billing catalog. Add-ons already included or active cannot be purchased twice.', viewPlans: 'View plans', reviewBilling: 'Review billing', contactBillingAdmin: 'Ask an Owner or Admin to review billing options.', invalidPlan: 'The requested plan is not valid. Showing your organization’s real billing state instead.', selectedPlan: 'Plan selected for review', selectedPlanBody: 'This is a commercial intent only. It does not change access until billing confirms the subscription.', selectedPlanPrice: 'Plan price', continuePlanReview: 'Continue plan review', backToPricing: 'Back to pricing', focusLabel: 'Suggested extension', noDirectPurchase: 'Provider-backed add-on checkout is not enabled yet', noDirectPurchaseBody: 'RISCK COMPLY will not show a fake purchase button. Until the billing engine exposes a verified add-on checkout, Owners/Admins can compare the catalog and plan upgrade options here.', categories: { compliance: 'Compliance', platform: 'Platform', capacity: 'Capacity', branding: 'Branding' },
  },
  pt: {
    eyebrow: 'Centro de Upgrade', title: 'Saiba exatamente o que a sua organização pode usar — e o que desbloqueia a seguir.', subtitle: 'Esta área lê o plano atual e os add-ons ativos diretamente da autoridade de billing. Nada é desbloqueado por URL, modo demo ou estado do navegador.', currentPlan: 'Plano atual', planActive: 'Autoridade do plano ativa', activeAddOns: 'Add-ons ativos', billingAuthority: 'Acesso confirmado pelo billing', billingAuthorityBody: 'O acesso só muda depois de a autoridade de billing confirmar o plano ou add-on. Esta página nunca concede permissões sozinha.', included: 'Incluído', active: 'Ativo', available: 'Disponível', unavailable: 'Indisponível neste plano', requiresPlan: (plan) => `Requer ${plan} ou superior`, perMonth: '/mês', perYear: '/ano', includedWithEnterprise: 'Incluído no Enterprise', availableOn: 'Disponível em', dependencies: 'Dependências', catalogTitle: 'Extensões de funcionalidades disponíveis', catalogSubtitle: 'Preços e disponibilidade vêm do catálogo canónico de billing. Add-ons já incluídos ou ativos não podem ser comprados duas vezes.', viewPlans: 'Ver planos', reviewBilling: 'Rever billing', contactBillingAdmin: 'Peça a um Owner ou Admin para rever as opções de billing.', invalidPlan: 'O plano solicitado não é válido. Estamos a mostrar o estado real da organização.', selectedPlan: 'Plano selecionado para revisão', selectedPlanBody: 'Isto é apenas uma intenção comercial. O acesso não muda até o billing confirmar a subscrição.', selectedPlanPrice: 'Preço do plano', continuePlanReview: 'Continuar revisão do plano', backToPricing: 'Voltar ao pricing', focusLabel: 'Extensão sugerida', noDirectPurchase: 'O checkout de add-ons suportado pelo provider ainda não está ativo', noDirectPurchaseBody: 'A RISCK COMPLY não mostrará um botão de compra falso. Até o motor de billing expor um checkout de add-ons verificado, Owners/Admins podem comparar aqui o catálogo e as opções de upgrade de plano.', categories: { compliance: 'Compliance', platform: 'Plataforma', capacity: 'Capacidade', branding: 'Marca' },
  },
  es: {
    eyebrow: 'Centro de Upgrade', title: 'Sepa exactamente qué puede usar su organización y qué se desbloquea después.', subtitle: 'Esta área lee el plan actual y los add-ons activos desde la autoridad de billing. Nada se desbloquea por URL, modo demo o estado del navegador.', currentPlan: 'Plan actual', planActive: 'Autoridad del plan activa', activeAddOns: 'Add-ons activos', billingAuthority: 'Acceso confirmado por billing', billingAuthorityBody: 'El acceso cambia solo después de que billing confirme el plan o add-on. Esta página nunca concede permisos por sí sola.', included: 'Incluido', active: 'Activo', available: 'Disponible', unavailable: 'No disponible en este plan', requiresPlan: (plan) => `Requiere ${plan} o superior`, perMonth: '/mes', perYear: '/año', includedWithEnterprise: 'Incluido con Enterprise', availableOn: 'Disponible en', dependencies: 'Dependencias', catalogTitle: 'Extensiones de capacidad disponibles', catalogSubtitle: 'Los precios y la disponibilidad proceden del catálogo canónico de billing. Los add-ons incluidos o activos no pueden comprarse dos veces.', viewPlans: 'Ver planes', reviewBilling: 'Revisar billing', contactBillingAdmin: 'Pida a un Owner o Admin que revise las opciones de billing.', invalidPlan: 'El plan solicitado no es válido. Se muestra el estado real de la organización.', selectedPlan: 'Plan seleccionado para revisión', selectedPlanBody: 'Esto es solo una intención comercial. El acceso no cambia hasta que billing confirme la suscripción.', selectedPlanPrice: 'Precio del plan', continuePlanReview: 'Continuar revisión del plan', backToPricing: 'Volver a pricing', focusLabel: 'Extensión sugerida', noDirectPurchase: 'El checkout de add-ons respaldado por el proveedor aún no está habilitado', noDirectPurchaseBody: 'RISCK COMPLY no mostrará un botón de compra falso. Hasta que billing exponga un checkout verificado de add-ons, Owners/Admins pueden comparar aquí el catálogo y los upgrades.', categories: { compliance: 'Compliance', platform: 'Plataforma', capacity: 'Capacidad', branding: 'Marca' },
  },
  fr: {
    eyebrow: 'Centre de mise à niveau', title: 'Sachez exactement ce que votre organisation peut utiliser — et ce qui se débloque ensuite.', subtitle: 'Cet espace lit le plan actuel et les add-ons actifs depuis l’autorité de facturation. Rien n’est débloqué par une URL, un mode démo ou l’état du navigateur.', currentPlan: 'Plan actuel', planActive: 'Autorité du plan active', activeAddOns: 'Add-ons actifs', billingAuthority: 'Accès confirmé par la facturation', billingAuthorityBody: 'L’accès ne change qu’après confirmation du plan ou de l’add-on par la facturation. Cette page n’accorde jamais de droits seule.', included: 'Inclus', active: 'Actif', available: 'Disponible', unavailable: 'Indisponible avec ce plan', requiresPlan: (plan) => `Nécessite ${plan} ou supérieur`, perMonth: '/mois', perYear: '/an', includedWithEnterprise: 'Inclus avec Enterprise', availableOn: 'Disponible sur', dependencies: 'Dépendances', catalogTitle: 'Extensions de capacités disponibles', catalogSubtitle: 'Les prix et la disponibilité proviennent du catalogue de facturation canonique. Un add-on inclus ou actif ne peut pas être acheté deux fois.', viewPlans: 'Voir les plans', reviewBilling: 'Voir la facturation', contactBillingAdmin: 'Demandez à un Owner ou Admin de revoir les options de facturation.', invalidPlan: 'Le plan demandé est invalide. L’état réel de l’organisation est affiché.', selectedPlan: 'Plan sélectionné pour examen', selectedPlanBody: 'Il s’agit uniquement d’une intention commerciale. L’accès ne change pas avant confirmation de la souscription par la facturation.', selectedPlanPrice: 'Prix du plan', continuePlanReview: 'Continuer l’examen du plan', backToPricing: 'Retour au pricing', focusLabel: 'Extension suggérée', noDirectPurchase: 'Le checkout provider pour les add-ons n’est pas encore activé', noDirectPurchaseBody: 'RISCK COMPLY n’affichera pas de faux bouton d’achat. Tant que le moteur de facturation n’expose pas un checkout add-on vérifié, Owners/Admins peuvent comparer le catalogue et les upgrades ici.', categories: { compliance: 'Conformité', platform: 'Plateforme', capacity: 'Capacité', branding: 'Marque' },
  },
  it: {
    eyebrow: 'Centro Upgrade', title: 'Sapete esattamente cosa può usare la vostra organizzazione e cosa si sblocca dopo.', subtitle: 'Questa area legge piano e add-on attivi dall’autorità di billing. Nulla viene sbloccato da URL, modalità demo o stato del browser.', currentPlan: 'Piano attuale', planActive: 'Autorità del piano attiva', activeAddOns: 'Add-on attivi', billingAuthority: 'Accesso confermato dal billing', billingAuthorityBody: 'L’accesso cambia solo dopo la conferma del piano o add-on da parte del billing. Questa pagina non concede mai permessi autonomamente.', included: 'Incluso', active: 'Attivo', available: 'Disponibile', unavailable: 'Non disponibile su questo piano', requiresPlan: (plan) => `Richiede ${plan} o superiore`, perMonth: '/mese', perYear: '/anno', includedWithEnterprise: 'Incluso con Enterprise', availableOn: 'Disponibile su', dependencies: 'Dipendenze', catalogTitle: 'Estensioni di funzionalità disponibili', catalogSubtitle: 'Prezzi e disponibilità provengono dal catalogo canonico di billing. Gli add-on inclusi o attivi non possono essere acquistati due volte.', viewPlans: 'Vedi piani', reviewBilling: 'Rivedi billing', contactBillingAdmin: 'Chiedi a un Owner o Admin di rivedere le opzioni di billing.', invalidPlan: 'Il piano richiesto non è valido. Viene mostrato lo stato reale dell’organizzazione.', selectedPlan: 'Piano selezionato per revisione', selectedPlanBody: 'È solo un’intenzione commerciale. L’accesso non cambia finché il billing non conferma l’abbonamento.', selectedPlanPrice: 'Prezzo del piano', continuePlanReview: 'Continua revisione del piano', backToPricing: 'Torna al pricing', focusLabel: 'Estensione suggerita', noDirectPurchase: 'Il checkout provider per gli add-on non è ancora abilitato', noDirectPurchaseBody: 'RISCK COMPLY non mostrerà un falso pulsante di acquisto. Finché il billing non espone un checkout add-on verificato, Owners/Admins possono confrontare catalogo e upgrade qui.', categories: { compliance: 'Compliance', platform: 'Piattaforma', capacity: 'Capacità', branding: 'Branding' },
  },
  de: {
    eyebrow: 'Upgrade Center', title: 'Sehen Sie genau, was Ihre Organisation nutzen kann — und was als Nächstes freigeschaltet wird.', subtitle: 'Dieser Bereich liest den aktuellen Plan und aktive Add-ons aus der Billing-Autorität. Nichts wird durch URL, Demo-Modus oder Browserzustand freigeschaltet.', currentPlan: 'Aktueller Plan', planActive: 'Plan-Autorität aktiv', activeAddOns: 'Aktive Add-ons', billingAuthority: 'Durch Billing bestätigter Zugriff', billingAuthorityBody: 'Zugriff ändert sich erst, nachdem Billing Plan oder Add-on bestätigt hat. Diese Seite vergibt niemals selbst Berechtigungen.', included: 'Enthalten', active: 'Aktiv', available: 'Verfügbar', unavailable: 'Mit diesem Plan nicht verfügbar', requiresPlan: (plan) => `Benötigt ${plan} oder höher`, perMonth: '/Monat', perYear: '/Jahr', includedWithEnterprise: 'In Enterprise enthalten', availableOn: 'Verfügbar für', dependencies: 'Abhängigkeiten', catalogTitle: 'Verfügbare Funktionserweiterungen', catalogSubtitle: 'Preise und Verfügbarkeit stammen aus dem kanonischen Billing-Katalog. Enthaltene oder aktive Add-ons können nicht doppelt gekauft werden.', viewPlans: 'Pläne ansehen', reviewBilling: 'Billing prüfen', contactBillingAdmin: 'Bitten Sie einen Owner oder Admin, die Billing-Optionen zu prüfen.', invalidPlan: 'Der angeforderte Plan ist ungültig. Stattdessen wird der reale Organisationsstatus angezeigt.', selectedPlan: 'Plan zur Prüfung ausgewählt', selectedPlanBody: 'Dies ist nur eine kommerzielle Absicht. Zugriff ändert sich erst nach Bestätigung des Abonnements durch Billing.', selectedPlanPrice: 'Planpreis', continuePlanReview: 'Planprüfung fortsetzen', backToPricing: 'Zurück zum Pricing', focusLabel: 'Empfohlene Erweiterung', noDirectPurchase: 'Provider-gestützter Add-on-Checkout ist noch nicht aktiviert', noDirectPurchaseBody: 'RISCK COMPLY zeigt keinen falschen Kaufbutton. Bis Billing einen verifizierten Add-on-Checkout bereitstellt, können Owners/Admins hier Katalog und Plan-Upgrades vergleichen.', categories: { compliance: 'Compliance', platform: 'Plattform', capacity: 'Kapazität', branding: 'Branding' },
  },
};

export function getAddOnsCopy(locale: string) {
  const safeLocale = locales.includes(locale as Locale) ? (locale as Locale) : 'en';
  return copy[safeLocale];
}
