export const dashboardCopy = {
  en: {
    nav: { overview: 'Overview', aiInventory: 'AI Inventory', transparency: 'Transparency', assessments: 'Assessments', documents: 'Documents', procurement: 'Procurement', monitoring: 'Monitoring', billing: 'Billing' },
    common: { menu: 'Menu', logout: 'Log out', site: 'Site', dashboard: 'Dashboard', loading: 'Initializing enterprise console...', proRequired: 'Professional plan or higher required', system: 'System' },
    overview: { eyebrow: 'AI governance operating layer', title: 'Real-time compliance readiness.', subtitle: 'Inventory, assessments, documentation and continuous monitoring in an interface built for executive decisions.', liveConsole: 'Live console', complianceScore: 'Compliance Score', aiRiskScore: 'AI Risk Score', aiSystems: 'AI Systems', registeredSystems: 'Registered systems', documents: 'Documents', drafts: 'drafts', recentActivity: 'Recent activity', thisMonth: '+5% this month', medium: 'Medium', low: 'Low', high: 'High' },
    actions: { addAiSystem: 'Add AI System', newAssessment: 'New Assessment', generatePolicy: 'Generate Policy', checkPlan: 'Check Plan' },
    toasts: { noPermission: 'You do not have permission to change this workspace', aiSystemAdded: 'AI system added successfully', aiSystemError: 'Error creating AI system', assessmentCreated: 'Assessment created successfully', assessmentError: 'Error creating assessment', documentCreated: 'Document created successfully', documentError: 'Error creating document', monitoringPlanRequired: 'Monitoring is available only on Growth or Enterprise plans', monitoringSaved: 'Monitoring preferences saved', monitoringSaveError: 'Error saving preferences', invalidSession: 'Invalid session to start checkout', checkoutStartError: 'Could not start checkout' }
  },
  pt: {
    nav: { overview: 'Visão geral', aiInventory: 'Inventário de IA', transparency: 'Transparência', assessments: 'Avaliações', documents: 'Documentos', procurement: 'Procurement', monitoring: 'Monitoramento', billing: 'Faturamento' },
    common: { menu: 'Menu', logout: 'Sair', site: 'Site', dashboard: 'Dashboard', loading: 'Inicializando console enterprise...', proRequired: 'Plano Profissional ou superior necessário', system: 'Sistema' },
    overview: { eyebrow: 'Camada operacional de governança de IA', title: 'Prontidão de compliance em tempo real.', subtitle: 'Inventário, avaliações, documentação e monitoramento contínuo em uma interface construída para decisões executivas.', liveConsole: 'Console ao vivo', complianceScore: 'Score de compliance', aiRiskScore: 'Score de risco de IA', aiSystems: 'Sistemas de IA', registeredSystems: 'Sistemas registrados', documents: 'Documentos', drafts: 'rascunhos', recentActivity: 'Atividade recente', thisMonth: '+5% este mês', medium: 'Médio', low: 'Baixo', high: 'Alto' },
    actions: { addAiSystem: 'Adicionar Sistema de IA', newAssessment: 'Nova avaliação', generatePolicy: 'Gerar política', checkPlan: 'Verificar plano' },
    toasts: { noPermission: 'Sem permissão para alterar este workspace', aiSystemAdded: 'Sistema de IA adicionado com sucesso', aiSystemError: 'Erro ao criar sistema de IA', assessmentCreated: 'Avaliação criada com sucesso', assessmentError: 'Erro ao criar avaliação', documentCreated: 'Documento criado com sucesso', documentError: 'Erro ao criar documento', monitoringPlanRequired: 'Monitoramento disponível apenas no plano Growth ou Enterprise', monitoringSaved: 'Preferências de monitoramento salvas', monitoringSaveError: 'Erro ao salvar preferências', invalidSession: 'Sessão inválida para iniciar checkout', checkoutStartError: 'Não foi possível iniciar o checkout' }
  },
  es: {
    nav: { overview: 'Resumen', aiInventory: 'Inventario de IA', transparency: 'Transparencia', assessments: 'Evaluaciones', documents: 'Documentos', procurement: 'Compras', monitoring: 'Monitorización', billing: 'Facturación' },
    common: { menu: 'Menú', logout: 'Salir', site: 'Sitio', dashboard: 'Panel', loading: 'Inicializando consola enterprise...', proRequired: 'Se requiere plan Profesional o superior', system: 'Sistema' },
    overview: { eyebrow: 'Capa operativa de gobernanza de IA', title: 'Preparación de cumplimiento en tiempo real.', subtitle: 'Inventario, evaluaciones, documentación y monitorización continua en una interfaz para decisiones ejecutivas.', liveConsole: 'Consola en vivo', complianceScore: 'Puntuación de cumplimiento', aiRiskScore: 'Puntuación de riesgo de IA', aiSystems: 'Sistemas de IA', registeredSystems: 'Sistemas registrados', documents: 'Documentos', drafts: 'borradores', recentActivity: 'Actividad reciente', thisMonth: '+5% este mes', medium: 'Medio', low: 'Bajo', high: 'Alto' },
    actions: { addAiSystem: 'Añadir sistema de IA', newAssessment: 'Nueva evaluación', generatePolicy: 'Generar política', checkPlan: 'Verificar plan' },
    toasts: { noPermission: 'No tienes permiso para cambiar este workspace', aiSystemAdded: 'Sistema de IA añadido correctamente', aiSystemError: 'Error al crear sistema de IA', assessmentCreated: 'Evaluación creada correctamente', assessmentError: 'Error al crear evaluación', documentCreated: 'Documento creado correctamente', documentError: 'Error al crear documento', monitoringPlanRequired: 'La monitorización solo está disponible en Growth o Enterprise', monitoringSaved: 'Preferencias de monitorización guardadas', monitoringSaveError: 'Error al guardar preferencias', invalidSession: 'Sesión inválida para iniciar checkout', checkoutStartError: 'No se pudo iniciar el checkout' }
  },
  fr: {
    nav: { overview: 'Vue d’ensemble', aiInventory: 'Inventaire IA', transparency: 'Transparence', assessments: 'Évaluations', documents: 'Documents', procurement: 'Achats', monitoring: 'Surveillance', billing: 'Facturation' },
    common: { menu: 'Menu', logout: 'Déconnexion', site: 'Site', dashboard: 'Tableau de bord', loading: 'Initialisation de la console enterprise...', proRequired: 'Plan Professionnel ou supérieur requis', system: 'Système' },
    overview: { eyebrow: 'Couche opérationnelle de gouvernance IA', title: 'Préparation conformité en temps réel.', subtitle: 'Inventaire, évaluations, documentation et surveillance continue dans une interface pensée pour les décisions exécutives.', liveConsole: 'Console en direct', complianceScore: 'Score de conformité', aiRiskScore: 'Score de risque IA', aiSystems: 'Systèmes IA', registeredSystems: 'Systèmes enregistrés', documents: 'Documents', drafts: 'brouillons', recentActivity: 'Activité récente', thisMonth: '+5% ce mois-ci', medium: 'Moyen', low: 'Faible', high: 'Élevé' },
    actions: { addAiSystem: 'Ajouter un système IA', newAssessment: 'Nouvelle évaluation', generatePolicy: 'Générer une politique', checkPlan: 'Vérifier le plan' },
    toasts: { noPermission: 'Vous n’avez pas l’autorisation de modifier ce workspace', aiSystemAdded: 'Système IA ajouté avec succès', aiSystemError: 'Erreur lors de la création du système IA', assessmentCreated: 'Évaluation créée avec succès', assessmentError: 'Erreur lors de la création de l’évaluation', documentCreated: 'Document créé avec succès', documentError: 'Erreur lors de la création du document', monitoringPlanRequired: 'La surveillance est disponible uniquement avec Growth ou Enterprise', monitoringSaved: 'Préférences de surveillance enregistrées', monitoringSaveError: 'Erreur lors de l’enregistrement des préférences', invalidSession: 'Session invalide pour démarrer le checkout', checkoutStartError: 'Impossible de démarrer le checkout' }
  },
  it: {
    nav: { overview: 'Panoramica', aiInventory: 'Inventario IA', transparency: 'Trasparenza', assessments: 'Valutazioni', documents: 'Documenti', procurement: 'Acquisti', monitoring: 'Monitoraggio', billing: 'Fatturazione' },
    common: { menu: 'Menu', logout: 'Esci', site: 'Sito', dashboard: 'Dashboard', loading: 'Inizializzazione console enterprise...', proRequired: 'Richiesto piano Professionale o superiore', system: 'Sistema' },
    overview: { eyebrow: 'Livello operativo di governance IA', title: 'Prontezza compliance in tempo reale.', subtitle: 'Inventario, valutazioni, documentazione e monitoraggio continuo in un’interfaccia per decisioni executive.', liveConsole: 'Console live', complianceScore: 'Punteggio compliance', aiRiskScore: 'Punteggio rischio IA', aiSystems: 'Sistemi IA', registeredSystems: 'Sistemi registrati', documents: 'Documenti', drafts: 'bozze', recentActivity: 'Attività recente', thisMonth: '+5% questo mese', medium: 'Medio', low: 'Basso', high: 'Alto' },
    actions: { addAiSystem: 'Aggiungi sistema IA', newAssessment: 'Nuova valutazione', generatePolicy: 'Genera policy', checkPlan: 'Verifica piano' },
    toasts: { noPermission: 'Non hai il permesso di modificare questo workspace', aiSystemAdded: 'Sistema IA aggiunto con successo', aiSystemError: 'Errore nella creazione del sistema IA', assessmentCreated: 'Valutazione creata con successo', assessmentError: 'Errore nella creazione della valutazione', documentCreated: 'Documento creato con successo', documentError: 'Errore nella creazione del documento', monitoringPlanRequired: 'Il monitoraggio è disponibile solo nei piani Growth o Enterprise', monitoringSaved: 'Preferenze di monitoraggio salvate', monitoringSaveError: 'Errore nel salvataggio delle preferenze', invalidSession: 'Sessione non valida per avviare il checkout', checkoutStartError: 'Impossibile avviare il checkout' }
  },
  de: {
    nav: { overview: 'Übersicht', aiInventory: 'KI-Inventar', transparency: 'Transparenz', assessments: 'Bewertungen', documents: 'Dokumente', procurement: 'Beschaffung', monitoring: 'Monitoring', billing: 'Abrechnung' },
    common: { menu: 'Menü', logout: 'Abmelden', site: 'Website', dashboard: 'Dashboard', loading: 'Enterprise-Konsole wird initialisiert...', proRequired: 'Professional-Plan oder höher erforderlich', system: 'System' },
    overview: { eyebrow: 'Operative KI-Governance-Ebene', title: 'Compliance-Bereitschaft in Echtzeit.', subtitle: 'Inventar, Bewertungen, Dokumentation und kontinuierliches Monitoring in einer Oberfläche für Management-Entscheidungen.', liveConsole: 'Live-Konsole', complianceScore: 'Compliance-Score', aiRiskScore: 'KI-Risiko-Score', aiSystems: 'KI-Systeme', registeredSystems: 'Registrierte Systeme', documents: 'Dokumente', drafts: 'Entwürfe', recentActivity: 'Aktuelle Aktivität', thisMonth: '+5% diesen Monat', medium: 'Mittel', low: 'Niedrig', high: 'Hoch' },
    actions: { addAiSystem: 'KI-System hinzufügen', newAssessment: 'Neue Bewertung', generatePolicy: 'Richtlinie erstellen', checkPlan: 'Plan prüfen' },
    toasts: { noPermission: 'Sie haben keine Berechtigung, diesen Workspace zu ändern', aiSystemAdded: 'KI-System erfolgreich hinzugefügt', aiSystemError: 'Fehler beim Erstellen des KI-Systems', assessmentCreated: 'Bewertung erfolgreich erstellt', assessmentError: 'Fehler beim Erstellen der Bewertung', documentCreated: 'Dokument erfolgreich erstellt', documentError: 'Fehler beim Erstellen des Dokuments', monitoringPlanRequired: 'Monitoring ist nur in Growth oder Enterprise verfügbar', monitoringSaved: 'Monitoring-Einstellungen gespeichert', monitoringSaveError: 'Fehler beim Speichern der Einstellungen', invalidSession: 'Ungültige Sitzung für Checkout', checkoutStartError: 'Checkout konnte nicht gestartet werden' }
  }
} as const;

export function getDashboardCopy(locale: string) {
  return dashboardCopy[locale as keyof typeof dashboardCopy] ?? dashboardCopy.en;
}
