import { locales, type Locale } from '@/lib/i18n/routing';

type TeamWorkflowCopy = {
  page: { eyebrow: string; title: string; body: string; badges: string[] };
  section: { eyebrow: string; title: string; body: string; verifyTitle: string; verifyBody: string; actionFailed: string; cancelled: string };
  invite: { title: string; body: string; email: string; role: string; selectRole: string; admin: string; editor: string; viewer: string; send: string; sending: string; error: string };
  access: { title: string; members: string; noMembers: string; you: string; member: string; role: string; remove: string; removeConfirm: (name: string) => string; pending: string; noPending: string; cancel: string; cancelConfirm: (email: string) => string };
  email: { subject: (organization: string) => string; title: (organization: string) => string; invitedBy: string; body: (organization: string, role: string) => string; cta: string; role: string; secureLink: string; header: string; footer: string };
};

const COPY: Record<Locale, TeamWorkflowCopy> = {
  en: {
    page: { eyebrow: 'Organization administration', title: 'Team and Enterprise access', body: 'Manage members and invitations, then supervise access controls and audit-ready operations.', badges: ['Tenant-scoped', 'Step-up protected', 'Access controlled', 'Audit evidence'] },
    section: { eyebrow: 'Team', title: 'Manage access', body: 'Invite teammates, review pending invitations, and keep access aligned with compliance responsibilities.', verifyTitle: 'Verify team management', verifyBody: 'Team invitations and access changes require MFA or enterprise identity verification.', actionFailed: 'Team action failed.', cancelled: 'Security verification was cancelled.' },
    invite: { title: 'Invite team member', body: 'Add collaborators to help manage compliance work.', email: 'Email', role: 'Role', selectRole: 'Select role', admin: 'Admin', editor: 'Editor', viewer: 'Viewer', send: 'Send invitation', sending: 'Sending...', error: 'Could not send invitation.' },
    access: { title: 'Team access', members: 'Members', noMembers: 'No team members found.', you: 'You', member: 'Team member', role: 'Role', remove: 'Remove', removeConfirm: (name) => `Remove ${name} from this organization?`, pending: 'Pending invitations', noPending: 'No pending invitations.', cancel: 'Cancel', cancelConfirm: (email) => `Cancel the invitation for ${email}?` },
    email: { subject: (org) => `Invitation to join ${org} on Risck Comply`, title: (org) => `Join ${org} on Risck Comply`, invitedBy: 'You were invited', body: (org, role) => `You were invited to join ${org} as ${role}.`, cta: 'Review invitation', role: 'Role', secureLink: 'Use the secure invitation link below. Do not forward this email.', header: 'AI governance operations for growing teams', footer: 'Message sent by Risck Comply.' },
  },
  pt: {
    page: { eyebrow: 'Administração da organização', title: 'Equipa e acesso Enterprise', body: 'Gira membros e convites e acompanhe controlos de acesso e operações prontas para auditoria.', badges: ['Âmbito da organização', 'Protegido por verificação', 'Acesso controlado', 'Evidência de auditoria'] },
    section: { eyebrow: 'Equipa', title: 'Gerir acesso', body: 'Convide colegas, reveja convites pendentes e mantenha o acesso alinhado com as responsabilidades de compliance.', verifyTitle: 'Verificar gestão da equipa', verifyBody: 'Convites e alterações de acesso exigem MFA ou verificação de identidade Enterprise.', actionFailed: 'A ação da equipa falhou.', cancelled: 'A verificação de segurança foi cancelada.' },
    invite: { title: 'Convidar membro da equipa', body: 'Adicione colaboradores para ajudar a gerir o trabalho de compliance.', email: 'Email', role: 'Função', selectRole: 'Selecionar função', admin: 'Administrador', editor: 'Editor', viewer: 'Visualizador', send: 'Enviar convite', sending: 'A enviar...', error: 'Não foi possível enviar o convite.' },
    access: { title: 'Acesso da equipa', members: 'Membros', noMembers: 'Nenhum membro encontrado.', you: 'Você', member: 'Membro da equipa', role: 'Função', remove: 'Remover', removeConfirm: (name) => `Remover ${name} desta organização?`, pending: 'Convites pendentes', noPending: 'Nenhum convite pendente.', cancel: 'Cancelar', cancelConfirm: (email) => `Cancelar o convite para ${email}?` },
    email: { subject: (org) => `Convite para entrar em ${org} no Risck Comply`, title: (org) => `Entre em ${org} no Risck Comply`, invitedBy: 'Foi convidado', body: (org, role) => `Foi convidado para entrar em ${org} com a função ${role}.`, cta: 'Rever convite', role: 'Função', secureLink: 'Use o link seguro abaixo. Não reencaminhe este email.', header: 'Operações de governação de IA para equipas em crescimento', footer: 'Mensagem enviada pelo Risck Comply.' },
  },
  es: {
    page: { eyebrow: 'Administración de la organización', title: 'Equipo y acceso Enterprise', body: 'Gestiona miembros e invitaciones y supervisa controles de acceso y operaciones preparadas para auditoría.', badges: ['Ámbito de organización', 'Protegido por verificación', 'Acceso controlado', 'Evidencia de auditoría'] },
    section: { eyebrow: 'Equipo', title: 'Gestionar acceso', body: 'Invita a compañeros, revisa invitaciones pendientes y mantén el acceso alineado con las responsabilidades de compliance.', verifyTitle: 'Verificar gestión del equipo', verifyBody: 'Las invitaciones y cambios de acceso requieren MFA o verificación de identidad Enterprise.', actionFailed: 'La acción del equipo ha fallado.', cancelled: 'La verificación de seguridad fue cancelada.' },
    invite: { title: 'Invitar miembro del equipo', body: 'Añade colaboradores para ayudar a gestionar el trabajo de compliance.', email: 'Email', role: 'Rol', selectRole: 'Seleccionar rol', admin: 'Administrador', editor: 'Editor', viewer: 'Visualizador', send: 'Enviar invitación', sending: 'Enviando...', error: 'No se pudo enviar la invitación.' },
    access: { title: 'Acceso del equipo', members: 'Miembros', noMembers: 'No se encontraron miembros.', you: 'Tú', member: 'Miembro del equipo', role: 'Rol', remove: 'Eliminar', removeConfirm: (name) => `¿Eliminar a ${name} de esta organización?`, pending: 'Invitaciones pendientes', noPending: 'No hay invitaciones pendientes.', cancel: 'Cancelar', cancelConfirm: (email) => `¿Cancelar la invitación para ${email}?` },
    email: { subject: (org) => `Invitación para unirte a ${org} en Risck Comply`, title: (org) => `Únete a ${org} en Risck Comply`, invitedBy: 'Has recibido una invitación', body: (org, role) => `Has sido invitado a unirte a ${org} con el rol ${role}.`, cta: 'Revisar invitación', role: 'Rol', secureLink: 'Usa el enlace seguro de abajo. No reenvíes este email.', header: 'Operaciones de gobernanza de IA para equipos en crecimiento', footer: 'Mensaje enviado por Risck Comply.' },
  },
  fr: {
    page: { eyebrow: 'Administration de l’organisation', title: 'Équipe et accès Enterprise', body: 'Gérez les membres et invitations, puis supervisez les contrôles d’accès et les opérations prêtes pour audit.', badges: ['Périmètre organisation', 'Vérification renforcée', 'Accès contrôlé', 'Preuve d’audit'] },
    section: { eyebrow: 'Équipe', title: 'Gérer les accès', body: 'Invitez des collègues, examinez les invitations en attente et alignez les accès sur les responsabilités de conformité.', verifyTitle: 'Vérifier la gestion de l’équipe', verifyBody: 'Les invitations et modifications d’accès exigent une MFA ou une vérification d’identité Enterprise.', actionFailed: 'L’action d’équipe a échoué.', cancelled: 'La vérification de sécurité a été annulée.' },
    invite: { title: 'Inviter un membre', body: 'Ajoutez des collaborateurs pour gérer le travail de conformité.', email: 'E-mail', role: 'Rôle', selectRole: 'Sélectionner un rôle', admin: 'Administrateur', editor: 'Éditeur', viewer: 'Lecteur', send: 'Envoyer l’invitation', sending: 'Envoi...', error: 'Impossible d’envoyer l’invitation.' },
    access: { title: 'Accès de l’équipe', members: 'Membres', noMembers: 'Aucun membre trouvé.', you: 'Vous', member: 'Membre de l’équipe', role: 'Rôle', remove: 'Retirer', removeConfirm: (name) => `Retirer ${name} de cette organisation ?`, pending: 'Invitations en attente', noPending: 'Aucune invitation en attente.', cancel: 'Annuler', cancelConfirm: (email) => `Annuler l’invitation pour ${email} ?` },
    email: { subject: (org) => `Invitation à rejoindre ${org} sur Risck Comply`, title: (org) => `Rejoignez ${org} sur Risck Comply`, invitedBy: 'Vous avez reçu une invitation', body: (org, role) => `Vous êtes invité à rejoindre ${org} avec le rôle ${role}.`, cta: 'Examiner l’invitation', role: 'Rôle', secureLink: 'Utilisez le lien sécurisé ci-dessous. Ne transférez pas cet e-mail.', header: 'Opérations de gouvernance IA pour équipes en croissance', footer: 'Message envoyé par Risck Comply.' },
  },
  it: {
    page: { eyebrow: 'Amministrazione organizzazione', title: 'Team e accesso Enterprise', body: 'Gestisci membri e inviti e supervisiona controlli di accesso e operazioni pronte per audit.', badges: ['Ambito organizzazione', 'Verifica protetta', 'Accesso controllato', 'Evidenza di audit'] },
    section: { eyebrow: 'Team', title: 'Gestisci accesso', body: 'Invita colleghi, controlla gli inviti in sospeso e mantieni l’accesso coerente con le responsabilità di compliance.', verifyTitle: 'Verifica gestione team', verifyBody: 'Inviti e modifiche di accesso richiedono MFA o verifica identità Enterprise.', actionFailed: 'L’azione del team non è riuscita.', cancelled: 'La verifica di sicurezza è stata annullata.' },
    invite: { title: 'Invita membro del team', body: 'Aggiungi collaboratori per gestire il lavoro di compliance.', email: 'Email', role: 'Ruolo', selectRole: 'Seleziona ruolo', admin: 'Amministratore', editor: 'Editor', viewer: 'Visualizzatore', send: 'Invia invito', sending: 'Invio...', error: 'Impossibile inviare l’invito.' },
    access: { title: 'Accesso team', members: 'Membri', noMembers: 'Nessun membro trovato.', you: 'Tu', member: 'Membro del team', role: 'Ruolo', remove: 'Rimuovi', removeConfirm: (name) => `Rimuovere ${name} da questa organizzazione?`, pending: 'Inviti in sospeso', noPending: 'Nessun invito in sospeso.', cancel: 'Annulla', cancelConfirm: (email) => `Annullare l’invito per ${email}?` },
    email: { subject: (org) => `Invito a entrare in ${org} su Risck Comply`, title: (org) => `Entra in ${org} su Risck Comply`, invitedBy: 'Hai ricevuto un invito', body: (org, role) => `Sei stato invitato a entrare in ${org} con il ruolo ${role}.`, cta: 'Rivedi invito', role: 'Ruolo', secureLink: 'Usa il link sicuro qui sotto. Non inoltrare questa email.', header: 'Operazioni di governance IA per team in crescita', footer: 'Messaggio inviato da Risck Comply.' },
  },
  de: {
    page: { eyebrow: 'Organisationsverwaltung', title: 'Team und Enterprise-Zugriff', body: 'Verwalten Sie Mitglieder und Einladungen sowie Zugriffskontrollen und auditfähige Abläufe.', badges: ['Organisationsbezogen', 'Verifizierung geschützt', 'Zugriff kontrolliert', 'Audit-Nachweis'] },
    section: { eyebrow: 'Team', title: 'Zugriff verwalten', body: 'Laden Sie Teammitglieder ein, prüfen Sie offene Einladungen und richten Sie Zugriffe an Compliance-Verantwortlichkeiten aus.', verifyTitle: 'Teamverwaltung verifizieren', verifyBody: 'Einladungen und Zugriffsänderungen erfordern MFA oder Enterprise-Identitätsprüfung.', actionFailed: 'Teamaktion fehlgeschlagen.', cancelled: 'Die Sicherheitsprüfung wurde abgebrochen.' },
    invite: { title: 'Teammitglied einladen', body: 'Fügen Sie Mitwirkende hinzu, um Compliance-Arbeit gemeinsam zu verwalten.', email: 'E-Mail', role: 'Rolle', selectRole: 'Rolle auswählen', admin: 'Administrator', editor: 'Editor', viewer: 'Betrachter', send: 'Einladung senden', sending: 'Wird gesendet...', error: 'Einladung konnte nicht gesendet werden.' },
    access: { title: 'Teamzugriff', members: 'Mitglieder', noMembers: 'Keine Teammitglieder gefunden.', you: 'Sie', member: 'Teammitglied', role: 'Rolle', remove: 'Entfernen', removeConfirm: (name) => `${name} aus dieser Organisation entfernen?`, pending: 'Offene Einladungen', noPending: 'Keine offenen Einladungen.', cancel: 'Abbrechen', cancelConfirm: (email) => `Einladung für ${email} abbrechen?` },
    email: { subject: (org) => `Einladung zu ${org} auf Risck Comply`, title: (org) => `${org} auf Risck Comply beitreten`, invitedBy: 'Sie wurden eingeladen', body: (org, role) => `Sie wurden eingeladen, ${org} mit der Rolle ${role} beizutreten.`, cta: 'Einladung prüfen', role: 'Rolle', secureLink: 'Verwenden Sie den sicheren Einladungslink unten. Leiten Sie diese E-Mail nicht weiter.', header: 'KI-Governance-Abläufe für wachsende Teams', footer: 'Nachricht von Risck Comply.' },
  },
};

export function getTeamWorkflowCopy(locale: string): TeamWorkflowCopy {
  const safeLocale = locales.includes(locale as Locale) ? (locale as Locale) : 'en';
  return COPY[safeLocale];
}
