insert into public.intelligence_items (
  external_id,
  title,
  category,
  jurisdiction,
  source_name,
  source_type,
  author,
  published_at,
  reliability,
  impact,
  executive_summary,
  internal_analysis,
  affected_companies,
  recommended_actions,
  reference_label,
  content_rights,
  full_text_allowed,
  premium,
  status
)
values
(
  'eu-ai-act-high-risk-readiness',
  'EU AI Act: empresas devem preparar evidências para sistemas de IA de alto risco',
  'AI Act',
  'União Europeia',
  'European Commission / EU AI Act policy pages',
  'institution',
  'EuroComply Intelligence Desk',
  '2026-06-10T12:00:00Z',
  'high',
  'high',
  'Empresas que usam ou fornecem sistemas de IA com impacto em pessoas precisam manter inventário, gestão de risco, documentação, supervisão humana e logs auditáveis.',
  'A organização deve mapear sistemas de IA, confirmar o papel contratual e anexar evidências por obrigação. O maior risco é tratar uso operacional externo como simples ferramenta interna.',
  array[''SaaS B2B'', ''Fintech'', ''RH e recrutamento'', ''Educação'', ''Healthtech''],
  array[''Atualizar inventário de IA.'', ''Classificar risco AI Act.'', ''Criar revisão para sistemas com clientes.'', ''Separar evidências de logs e transparência.''],
  'EU AI Act institutional monitoring',
  'metadata_and_analysis_only',
  false,
  false,
  'published'
),
(
  'edpb-ai-gdpr-transparency',
  'IA e RGPD: transparência e base legal continuam centrais para uso corporativo de modelos',
  'RGPD / Dados pessoais',
  'União Europeia',
  'EDPB / autoridades europeias de proteção de dados',
  'regulator',
  'EuroComply Intelligence Desk',
  '2026-06-08T12:00:00Z',
  'high',
  'medium',
  'Empresas que usam IA com dados pessoais precisam demonstrar finalidade, minimização, transparência, controle de acesso, retenção e base legal adequada.',
  'O cliente deve revisar política de uso aceitável de IA, DPIA quando houver alto risco e fornecedores que processam dados fora da empresa.',
  array[''E-commerce'', ''SaaS com suporte ao cliente'', ''Consultorias'', ''Empresas com CRM''],
  array[''Revisar política interna de IA.'', ''Adicionar fornecedores de IA ao registro de terceiros.'', ''Criar evidência de base legal.'', ''Treinar equipes que usam prompts.''],
  'European data protection monitoring',
  'metadata_and_analysis_only',
  false,
  false,
  'published'
),
(
  'nis2-dora-technology-governance',
  'Governança tecnológica: NIS2 e DORA elevam pressão sobre risco de terceiros e incidentes',
  'Cibersegurança / Terceiros',
  'União Europeia',
  'ENISA / autoridades nacionais competentes',
  'official',
  'EuroComply Intelligence Desk',
  '2026-06-05T12:00:00Z',
  'high',
  'high',
  'Empresas reguladas e fornecedores críticos precisam mostrar rastreabilidade de incidentes, continuidade operacional, fornecedores essenciais e evidências de resposta.',
  'A notícia deve acionar revisão de vendors críticos, SLAs, DPA, incident response e continuidade. O calendário inteligente deve sugerir revisão periódica.',
  array[''Fintech'', ''SaaS corporativo'', ''Cloud providers'', ''Empresas com fornecedores críticos''],
  array[''Marcar fornecedores críticos.'', ''Validar plano de continuidade.'', ''Testar resposta a incidentes.'', ''Atualizar subprocessadores.''],
  'Cyber resilience monitoring',
  'metadata_and_analysis_only',
  false,
  true,
  'published'
)
on conflict (external_id) do update set
  title = excluded.title,
  category = excluded.category,
  jurisdiction = excluded.jurisdiction,
  source_name = excluded.source_name,
  source_type = excluded.source_type,
  author = excluded.author,
  published_at = excluded.published_at,
  reliability = excluded.reliability,
  impact = excluded.impact,
  executive_summary = excluded.executive_summary,
  internal_analysis = excluded.internal_analysis,
  affected_companies = excluded.affected_companies,
  recommended_actions = excluded.recommended_actions,
  reference_label = excluded.reference_label,
  content_rights = excluded.content_rights,
  full_text_allowed = excluded.full_text_allowed,
  premium = excluded.premium,
  status = excluded.status,
  updated_at = now();
