import type { LocalizedFeaturePages } from './types';

export const deFeaturePages: LocalizedFeaturePages = {
  'ai-inventory': {
    key: 'ai-inventory',
    slug: 'ki-inventar',
    navLabel: 'KI-Inventar',
    title: 'Software für ein KI-Systeminventar in europäischen Teams',
    description: 'Erstellen Sie ein strukturiertes Inventar für KI-Systeme, Anwendungsfälle, Verantwortliche, Anbieter, Länder, Datenkontext und Prüfstatus.',
    eyebrow: 'KI-Systeminventar',
    intro: 'Bauen Sie ein verlässliches Register der KI-Systeme auf, die Ihr Unternehmen nutzt, einkauft, entwickelt oder betreibt. RISCK COMPLY ersetzt verteilte Tabellen durch verantwortbare und prüfbare Datensätze.',
    problemTitle: 'Verantwortung für KI darf nicht zwischen Tabellen und E-Mails verloren gehen',
    problem: 'Governance wird schwierig, wenn Systeme, Verantwortliche, Anbieter und Nachweise in getrennten Werkzeugen liegen. Ein strukturiertes Inventar bildet die operative Grundlage für Risikoprüfung, Dokumentation und Monitoring.',
    capabilitiesTitle: 'Was das KI-Inventar abbilden kann',
    capabilities: ['Name, Zweck, Abteilung, Verantwortlicher und Lebenszyklusstatus', 'Anbieter, Bereitstellungsmodell, Länder und betroffene Prozesse', 'Datenkategorien, Nutzer, Integrationen und Dokumentation', 'Risikosignale, Bewertungsstatus, Nachweislücken und Maßnahmen'],
    workflowTitle: 'Ein praktischer Inventarprozess',
    workflow: ['System und Anwendungsfall erfassen', 'Verantwortliche und Prüfer zuweisen', 'Anbieter-, Daten- und Bereitstellungskontext dokumentieren', 'Bewertungen, Nachweise, Aufgaben und Monitoring verbinden'],
    faqTitle: 'Fragen zum KI-Inventar',
    faq: [
      { question: 'Was ist ein KI-Systeminventar?', answer: 'Ein strukturiertes Register der KI-Systeme, die ein Unternehmen entwickelt, beschafft oder nutzt, einschließlich Zweck, Verantwortung, Anbieter, Risikokontext und Nachweisen.' },
      { question: 'Garantiert ein Inventar die Einhaltung des AI Act?', answer: 'Nein. Es unterstützt Governance und Nachweisvorbereitung, aber Pflichten hängen vom Unternehmen, seiner Rolle, dem System und dem anwendbaren Recht ab.' },
      { question: 'Können bestehende Tabellen übernommen werden?', answer: 'RISCK COMPLY ist für die strukturierte Übernahme bestehender Datensätze ausgelegt und erhält Verantwortungs- und Prüfkontext.' },
    ],
    ctaTitle: 'Schaffen Sie eine operative Quelle für alle KI-Systeme',
    ctaText: 'Organisieren Sie Systeme, Verantwortliche, Risiken und Nachweise in einem kontrollierten Workspace für europäische B2B-Teams.',
  },
  'ai-risk-assessment': {
    key: 'ai-risk-assessment',
    slug: 'ki-risikobewertung',
    navLabel: 'KI-Risikobewertung',
    title: 'Software für KI-Risikobewertungen und nachvollziehbare Prüfworkflows',
    description: 'Erfassen Sie Risikosignale, Kontext, Entscheidungen, Verantwortliche und Maßnahmen in nachvollziehbaren Workflows für europäische B2B-Teams.',
    eyebrow: 'KI-Risikobewertung',
    intro: 'Machen Sie Risikoprüfung zu einem wiederholbaren Prozess. Sammeln Sie Kontext, beziehen Sie die richtigen Rollen ein und verbinden Sie Entscheidungen mit den betroffenen Systemen und Nachweisen.',
    problemTitle: 'Risikobewertungen brauchen Kontext, Verantwortung und Historie',
    problem: 'Ein Risikolabel allein reicht nicht aus. Teams müssen Anwendungsfall, betroffene Personen, Daten, Automatisierungsgrad, Anbieterabhängigkeiten und Kontrollen hinter jeder Schlussfolgerung verstehen.',
    capabilitiesTitle: 'Strukturieren Sie den gesamten Prüfungskontext',
    capabilities: ['Signale zu Nutzung, Auswirkungen, Daten, Nutzern und Bereitstellung', 'Erste Einstufung, Prüfstatus und dokumentierte Begründung', 'Verantwortliche, Maßnahmen und Freigabepunkte', 'Verknüpfte Nachweise, Richtlinien, Anbieter und Aktivitätshistorie'],
    workflowTitle: 'Von der Erfassung zur geprüften Entscheidung',
    workflow: ['System- und Anwendungsfallkontext erfassen', 'Relevante Risikosignale dokumentieren', 'Prüfer und Nachweisanfragen zuweisen', 'Ergebnisse, Maßnahmen und Monitoring dokumentieren'],
    faqTitle: 'Fragen zur KI-Risikobewertung',
    faq: [
      { question: 'Ist dies ein automatisches juristisches Klassifizierungstool?', answer: 'Nein. RISCK COMPLY unterstützt strukturierte Readiness- und Risikoworkflows, ersetzt aber keine qualifizierte Rechtsbewertung und garantiert keine Einstufung.' },
      { question: 'Können Bewertungen erneut geprüft werden?', answer: 'Ja. Eine erneute Prüfung ist sinnvoll, wenn sich System, Anwendungsfall, Anbieter, Daten oder Rechtskontext ändern.' },
      { question: 'Wer sollte teilnehmen?', answer: 'Je nach Anwendungsfall Produkt, Engineering, Sicherheit, Datenschutz, Recht, Compliance, Einkauf und der Business Owner.' },
    ],
    ctaTitle: 'Machen Sie Risikoprüfung wiederholbar und nachvollziehbar',
    ctaText: 'Bringen Sie Kontext, Entscheidungen, Verantwortliche und Nachweise zusammen statt sie in getrennten Dokumenten zu verwalten.',
  },
  'evidence-management': {
    key: 'evidence-management',
    slug: 'nachweismanagement',
    navLabel: 'Nachweismanagement',
    title: 'Software für KI-Compliance-Nachweise und Evidenzmanagement',
    description: 'Organisieren Sie KI-Governance-Nachweise, Dokumente, Entscheidungen, Verantwortliche und Prüfstatus in strukturierten Paketen.',
    eyebrow: 'Compliance-Nachweismanagement',
    intro: 'Behandeln Sie Nachweise als operativen Prozess statt als kurzfristige Dateisuche. RISCK COMPLY verbindet Datensätze, Entscheidungen und Dateien mit den Systemen und Kontrollen, die sie unterstützen.',
    problemTitle: 'Nachweise verlieren ihren Wert, wenn unklar ist, was sie belegen',
    problem: 'Dateien in allgemeinen Ordnern zeigen selten, zu welchem System, welcher Kontrolle, Entscheidung oder Verantwortung sie gehören. Strukturiertes Management erhält den Kontext und beschleunigt Prüfungen.',
    capabilitiesTitle: 'Erstellen Sie Nachweispakete mit klarem Kontext',
    capabilities: ['Dokumente mit Systemen, Bewertungen und Kontrollen verbinden', 'Verantwortliche, Status, Daten und fehlende Elemente verfolgen', 'Entscheidungen und Begründungen mit Anhängen dokumentieren', 'Abgegrenzte Pakete für Recht, Sicherheit, Einkauf oder Audit vorbereiten'],
    workflowTitle: 'Von der Anforderung zum prüfbaren Nachweispaket',
    workflow: ['Nachweisanforderung definieren', 'Verantwortlichen und Termin zuweisen', 'Unterstützenden Datensatz anhängen oder erstellen', 'Vollständigkeit prüfen und Historie erhalten'],
    faqTitle: 'Fragen zum Nachweismanagement',
    faq: [
      { question: 'Was gehört in ein KI-Governance-Nachweispaket?', answer: 'Je nach System und Prüfbereich zum Beispiel Inventare, Bewertungen, Richtlinien, Freigaben, Anbieterinformationen, Tests und Monitoring-Nachweise.' },
      { question: 'Belegt ein gespeichertes Dokument die Wirksamkeit einer Kontrolle?', answer: 'Nein. Ein Nachweis muss relevant, aktuell und klar mit der Kontrolle oder Entscheidung verbunden sein, die er unterstützen soll.' },
      { question: 'Können Nachweise pro KI-System organisiert werden?', answer: 'Ja. Die Plattform verbindet Nachweise mit Systemen, Prüfungen, Verantwortlichen und Governance-Aktivitäten der Organisation.' },
    ],
    ctaTitle: 'Machen Sie aus verteilten Dateien prüfbare Governance-Nachweise',
    ctaText: 'Organisieren Sie Nachweise nach System, Verantwortlichem, Anforderung und Status, um vorhandene und fehlende Elemente zu erkennen.',
  },
  'ai-governance-workflows': {
    key: 'ai-governance-workflows',
    slug: 'ki-governance-workflows',
    navLabel: 'Governance-Workflows',
    title: 'KI-Governance-Workflow-Software für bereichsübergreifende Teams',
    description: 'Koordinieren Sie Intake, Verantwortung, Bewertungen, Freigaben, Nachweise und Monitoring zwischen Produkt, Recht, Sicherheit, Datenschutz und Compliance.',
    eyebrow: 'KI-Governance-Workflows',
    intro: 'Geben Sie jedem KI-System einen klaren Weg von der Erfassung bis zur laufenden Prüfung. Koordinieren Sie Verantwortung, ohne Governance in Tabellen und E-Mail-Ketten zu zerlegen.',
    problemTitle: 'Governance stockt ohne Verantwortlichen und nächsten Schritt',
    problem: 'KI-Governance ist bereichsübergreifend. Ohne sichtbare Verantwortlichkeiten, Prüfstatus und Eskalationswege bleiben wichtige Aufgaben trotz vorhandener Richtlinien offen.',
    capabilitiesTitle: 'Koordinieren Sie Governance-Arbeit an einem Ort',
    capabilities: ['Strukturierter Intake und Zuweisung von Verantwortung', 'Prüfphasen, Aufgaben, Fristen und Freigaben', 'Mit Systemen und Bewertungen verbundene Nachweisanfragen', 'Monitoring, Änderungsprüfung und nachvollziehbare Historie'],
    workflowTitle: 'Ein gemeinsamer operativer Ablauf',
    workflow: ['KI-Anwendungsfall erkennen und erfassen', 'Verantwortliche und Prüfer zuweisen', 'Risiken bewerten und Nachweise sammeln', 'Freigeben, dokumentieren und Änderungen überwachen'],
    faqTitle: 'Fragen zu Governance-Workflows',
    faq: [
      { question: 'Welche Teams können teilnehmen?', answer: 'Produkt, Engineering, Recht, Compliance, Datenschutz, Sicherheit, Einkauf und Business Owner.' },
      { question: 'Ersetzt der Workflow interne Richtlinien?', answer: 'Nein. Er unterstützt Ausführung und Nachweis der Prozesse; Richtlinien und Pflichten benötigen weiterhin geeignete Verantwortung und Prüfung.' },
      { question: 'Warum Aufgaben mit KI-Systemen verbinden?', answer: 'Die Verbindung erhält den Kontext, reduziert Unklarheit und zeigt, warum eine Aufgabe existiert und wer verantwortlich ist.' },
    ],
    ctaTitle: 'Betreiben Sie KI-Governance als echten Geschäftsprozess',
    ctaText: 'Schaffen Sie sichtbare Verantwortung, konsistente Prüfphasen und nachvollziehbare Maßnahmen für jedes KI-System.',
  },
  'vendor-ai-risk': {
    key: 'vendor-ai-risk',
    slug: 'ki-anbieterrisiko',
    navLabel: 'KI-Anbieterrisiko',
    title: 'Workflows für KI-Anbieterrisiken und Third-Party-Assurance',
    description: 'Verfolgen Sie KI-Anbieter, Dienste, Verträge, Datenkontext, Nachweisanfragen und Entscheidungen für Einkauf und Third-Party-Risk.',
    eyebrow: 'KI-Anbieterrisiko',
    intro: 'Verstehen Sie, welche Anbieter welche KI-Anwendungsfälle unterstützen und welche Nachweise vor Beschaffung, Einführung oder Verlängerung verfügbar sind.',
    problemTitle: 'Anbieterrisiko lässt sich nicht ohne Nutzungskontext bewerten',
    problem: 'Derselbe KI-Dienst kann je nach Daten, Nutzern, Integrationen und Geschäftsprozess unterschiedliche Risiken erzeugen. Anbieterprüfung braucht sowohl Anbieter-Nachweise als auch Systemkontext.',
    capabilitiesTitle: 'Verbinden Sie Anbieterprüfung mit der tatsächlichen Nutzung',
    capabilities: ['Anbieterprofil, Dienste, Regionen und verbundene Systeme', 'Nachweisanfragen zu Sicherheit, Datenschutz, Vertrag und Governance', 'Verantwortliche, Findings, Entscheidungen und Maßnahmen', 'Kontext zu Verlängerung, wesentlichen Änderungen und Abhängigkeiten'],
    workflowTitle: 'Eine strukturierte Anbieterprüfung',
    workflow: ['Anbieter und Anwendungsfall erfassen', 'Relevante Assurance-Nachweise anfordern', 'Findings mit Verantwortlichen prüfen', 'Entscheidungen, Bedingungen und Maßnahmen dokumentieren'],
    faqTitle: 'Fragen zum KI-Anbieterrisiko',
    faq: [
      { question: 'Ist Anbieterprüfung dasselbe wie Systembewertung?', answer: 'Nein. Assurance prüft Drittanbieter und Dienst; die Systembewertung betrachtet den konkreten Anwendungsfall, Auswirkungen und Kontrollen der Organisation. Beides sollte verbunden sein.' },
      { question: 'Welche Nachweise können angefordert werden?', answer: 'Zum Beispiel Sicherheitsdokumentation, Datenschutzbedingungen, Informationen zum Dienst oder Modell, Incident-Prozesse und vertragliche Zusagen.' },
      { question: 'Kann ein Anbieter mehreren Systemen zugeordnet werden?', answer: 'Ja. Ein Anbieter kann mehrere Systeme oder Prozesse unterstützen, jeweils mit unterschiedlicher Verantwortung und Risikokontext.' },
    ],
    ctaTitle: 'Machen Sie KI-Anbieterprüfungen operativ beherrschbar',
    ctaText: 'Verbinden Sie Anbieter, Systeme, Nachweisanfragen und Entscheidungen, damit Einkauf und Governance denselben Kontext nutzen.',
  },
  'eu-ai-act-readiness': {
    key: 'eu-ai-act-readiness',
    slug: 'ai-act-vorbereitung',
    navLabel: 'AI-Act-Vorbereitung',
    title: 'EU-AI-Act-Readiness-Plattform für europäische B2B-Teams',
    description: 'Organisieren Sie KI-Systeme, Verantwortlichkeiten, Risikokontext, Dokumentation und Nachweise für die praktische Vorbereitung auf den EU AI Act.',
    eyebrow: 'Vorbereitung auf den EU AI Act',
    intro: 'Bauen Sie die operativen Datensätze auf, die Ihr Team benötigt, um KI-Nutzung zu verstehen, Verantwortung zu koordinieren und Nachweise für rechtliche und Compliance-Prüfung vorzubereiten.',
    problemTitle: 'Readiness braucht mehr als eine einmalige Checkliste',
    problem: 'Systeme, Anbieter, Anwendungsfälle und rechtliche Auslegung verändern sich. Teams benötigen ein Betriebsmodell, das Inventar, Entscheidungen, Nachweise und Maßnahmen dauerhaft verbindet.',
    capabilitiesTitle: 'Unterstützen Sie Readiness über den gesamten Governance-Lebenszyklus',
    capabilities: ['KI-Inventar und Verantwortlichkeiten', 'Risikosignale, Bewertungen und Begründungen', 'Richtlinien, Nachweispakete und Anbieterdokumentation', 'Aufgaben, Freigaben, Monitoring und Aktivitätshistorie'],
    workflowTitle: 'Von Transparenz zur Nachweisvorbereitung',
    workflow: ['Systeme und organisatorische Rollen identifizieren', 'Anwendungsfälle und relevante Pflichten prüfen', 'Dokumentation und Nachweise vorbereiten', 'Änderungen, Lücken und laufende Maßnahmen prüfen'],
    faqTitle: 'Fragen zur EU-AI-Act-Vorbereitung',
    faq: [
      { question: 'Bietet RISCK COMPLY Rechtsberatung?', answer: 'Nein. Die Plattform unterstützt Governance-Prozesse und Nachweisvorbereitung. Unternehmen sollten für ihre konkreten Pflichten qualifizierte Rechtsberatung einholen.' },
      { question: 'Macht die Nutzung der Plattform ein Unternehmen compliant?', answer: 'Nein. Keine Software garantiert Compliance. Das Ergebnis hängt von Organisation, Systemen, Kontrollen, Nachweisen, Entscheidungen und rechtlicher Auslegung ab.' },
      { question: 'Welche Teams können die Plattform nutzen?', answer: 'B2B-Teams aus Compliance, Recht, Sicherheit, Datenschutz, Produkt, Engineering, Einkauf und KI-Governance.' },
    ],
    ctaTitle: 'Schaffen Sie eine operative Grundlage für den AI Act',
    ctaText: 'Organisieren Sie Systeme, Verantwortliche, Risiken, Dokumente und Nachweise, um Governance-Arbeit klar zu prüfen.',
  },
  'audit-trails': {
    key: 'audit-trails',
    slug: 'ki-audit-protokolle',
    navLabel: 'Audit-Protokolle',
    title: 'Audit-Protokolle und Aktivitätshistorie für KI-Governance',
    description: 'Halten Sie Governance-Aktionen, Änderungen, Entscheidungen und Nachweise für interne Prüfung, Untersuchung und Einkauf nachvollziehbar.',
    eyebrow: 'Governance-Aktivitätshistorie',
    intro: 'Bewahren Sie den Kontext wichtiger Governance-Aktivitäten. Prüfen Sie, wer Datensätze geändert hat, welche Entscheidung getroffen wurde und welche Nachweise sie unterstützt haben.',
    problemTitle: 'Ein Abschlussdokument erklärt selten den Weg zur Entscheidung',
    problem: 'Prüfer benötigen oft die Abfolge von Aktionen, Verantwortungsänderungen, Freigaben und Nachweisupdates. Eine nachvollziehbare Historie hilft, diesen Kontext zu rekonstruieren.',
    capabilitiesTitle: 'Halten Sie Governance-Aktivitäten prüfbar',
    capabilities: ['Historie von Systemen, Bewertungen und Nachweisen', 'Aktivitäten zu Verantwortlichen, Aufgaben und Freigaben', 'Kontext sicherheits- und compliance-relevanter Ereignisse', 'Abgegrenzte Datensätze für Prüfung und Untersuchung'],
    workflowTitle: 'Nutzen Sie die Historie in einer Prüfung',
    workflow: ['System oder Datensatz bestimmen', 'Ereignisse und verantwortliche Nutzer prüfen', 'Änderungen mit Entscheidungen und Nachweisen verbinden', 'Folge- oder Korrekturmaßnahmen dokumentieren'],
    faqTitle: 'Fragen zu Audit-Protokollen',
    faq: [
      { question: 'Sind die Protokolle rechtlich unveränderlich?', answer: 'RISCK COMPLY behauptet keine externe Unveränderlichkeit ohne gesonderten technischen Nachweis. Die Historie ist für Nachvollziehbarkeit und Prüfung ausgelegt.' },
      { question: 'Warum sind Audit-Protokolle nützlich?', answer: 'Sie helfen, Änderungen, Verantwortung und Entscheidungen zu verstehen und unterstützen interne Prüfung, Incident-Analyse und Beschaffungsdiligence.' },
      { question: 'Ersetzen sie formale Audit-Nachweise?', answer: 'Nein. Sie können ein Nachweispaket unterstützen, aber der erforderliche Beleg hängt von Umfang und Prüfer ab.' },
    ],
    ctaTitle: 'Halten Sie KI-Governance-Entscheidungen nachvollziehbar',
    ctaText: 'Bewahren Sie Aktivitätskontext über Systeme, Bewertungen, Nachweise und Folgemaßnahmen hinweg.',
  },
  'compliance-documentation': {
    key: 'compliance-documentation',
    slug: 'ki-compliance-dokumentation',
    navLabel: 'Compliance-Dokumentation',
    title: 'Software für KI-Governance- und Compliance-Dokumentation',
    description: 'Erstellen, organisieren und pflegen Sie Richtlinien, Register, Berichte und KI-Dokumentation mit klarer Verantwortung und Prüfstatus.',
    eyebrow: 'KI-Compliance-Dokumentation',
    intro: 'Erstellen Sie Dokumentation, die mit den Systemen, Entscheidungen und Nachweisen verbunden bleibt, die sie beschreibt. Halten Sie Verantwortliche und Prüftermine sichtbar.',
    problemTitle: 'Dokumentation veraltet, wenn sie vom Betrieb getrennt ist',
    problem: 'Richtlinien und Berichte lassen sich leichter pflegen, wenn sie mit aktuellen Systemen, Bewertungen, Verantwortlichen und Nachweisen verbunden sind statt zwischen isolierten Dateien kopiert zu werden.',
    capabilitiesTitle: 'Pflegen Sie Governance-Dokumentation mit operativem Kontext',
    capabilities: ['Richtlinien, Berichte, Register und prüfbare Zusammenfassungen', 'Verantwortlicher, Status, Version und Prüftermine', 'Verbindungen zu Systemen, Bewertungen, Nachweisen und Entscheidungen', 'Kontrollierte Vorbereitung für interne, rechtliche oder Beschaffungsprüfung'],
    workflowTitle: 'Ein nachhaltiger Dokumentationsprozess',
    workflow: ['Zweck und Umfang festlegen', 'Systeme, Verantwortliche und Nachweise verbinden', 'Inhalt erstellen und prüfen', 'Freigeben, veröffentlichen und nächste Prüfung planen'],
    faqTitle: 'Fragen zur Dokumentation',
    faq: [
      { question: 'Ersetzen generierte Dokumente die Rechtsprüfung?', answer: 'Nein. Generierte oder vorlagenbasierte Inhalte sollten von geeigneten Rechts-, Compliance- und Fachexperten geprüft werden.' },
      { question: 'Warum Dokumente mit Systemen verbinden?', answer: 'Die Verbindung macht den Umfang klar und erleichtert Aktualisierungen, wenn sich System, Anwendungsfall, Anbieter oder Bewertung ändern.' },
      { question: 'Welche Dokumente können organisiert werden?', answer: 'Zum Beispiel KI-Richtlinien, Inventare, Bewertungszusammenfassungen, Governance-Berichte, Anbieterunterlagen und Nachweispakete.' },
    ],
    ctaTitle: 'Verbinden Sie Governance-Dokumentation mit der tatsächlichen Arbeit',
    ctaText: 'Erstellen und pflegen Sie Dokumente mit sichtbarer Verantwortung, unterstützenden Nachweisen und Prüfstatus.',
  },
};
