import type { LocalizedFeaturePages } from './types';

export const enFeaturePages: LocalizedFeaturePages = {
  'ai-inventory': {
    key: 'ai-inventory',
    slug: 'ai-inventory',
    navLabel: 'AI inventory',
    title: 'AI System Inventory Software for European Teams',
    description: 'Create a structured inventory of AI systems, use cases, owners, providers, countries, data context and review status in one controlled workspace.',
    eyebrow: 'AI system inventory',
    intro: 'Build a reliable record of the AI systems your organization uses, buys, develops or operates. RISCK COMPLY helps teams replace fragmented spreadsheets with accountable, reviewable records.',
    problemTitle: 'Stop losing AI ownership across spreadsheets and inboxes',
    problem: 'Governance becomes difficult when systems, owners, providers and evidence are stored in separate tools. A structured inventory creates the operational foundation for risk review, documentation and ongoing monitoring.',
    capabilitiesTitle: 'What your AI inventory can organize',
    capabilities: [
      'AI system name, purpose, department, owner and lifecycle status',
      'Provider, deployment model, countries and affected business processes',
      'Data categories, users, integrations and supporting documentation',
      'Risk signals, assessment status, evidence gaps and follow-up actions',
    ],
    workflowTitle: 'A practical inventory workflow',
    workflow: ['Register the system and business use case', 'Assign accountable owners and reviewers', 'Capture provider, data and deployment context', 'Connect assessments, evidence, tasks and monitoring'],
    faqTitle: 'AI inventory questions',
    faq: [
      { question: 'What is an AI system inventory?', answer: 'It is a structured register of the AI systems an organization develops, procures or uses, including ownership, purpose, providers, risk context and supporting evidence.' },
      { question: 'Does an AI inventory guarantee EU AI Act compliance?', answer: 'No. An inventory supports governance and evidence preparation, but legal obligations depend on the organization, role, system and applicable law.' },
      { question: 'Can teams import existing spreadsheet records?', answer: 'RISCK COMPLY is designed to support structured onboarding and migration of existing records while preserving ownership and review context.' },
    ],
    ctaTitle: 'Create one operational source of truth for AI systems',
    ctaText: 'Start organizing systems, owners, risks and evidence in a controlled workspace built for European B2B teams.',
  },
  'ai-risk-assessment': {
    key: 'ai-risk-assessment',
    slug: 'ai-risk-assessment',
    navLabel: 'AI risk assessment',
    title: 'AI Risk Assessment Software and Review Workflows',
    description: 'Capture AI risk signals, assessment context, decisions, owners and follow-up actions with traceable review workflows for European B2B teams.',
    eyebrow: 'AI risk assessment',
    intro: 'Turn risk review into a repeatable operating process. Capture context, involve the right stakeholders and keep decisions linked to the systems and evidence they concern.',
    problemTitle: 'Risk decisions need context, ownership and an audit trail',
    problem: 'A risk label alone is not enough. Teams need to understand the use case, affected people, data, automation level, provider dependencies and controls behind each conclusion.',
    capabilitiesTitle: 'Structure the full review context',
    capabilities: [
      'Use-case, impact, data, user and deployment risk signals',
      'Initial classification, reviewer status and documented rationale',
      'Assigned owners, remediation tasks and approval checkpoints',
      'Linked evidence, policies, provider records and activity history',
    ],
    workflowTitle: 'Move from intake to reviewed decision',
    workflow: ['Collect system and use-case context', 'Record relevant risk signals', 'Assign reviewers and evidence requests', 'Document conclusions, actions and monitoring needs'],
    faqTitle: 'AI risk assessment questions',
    faq: [
      { question: 'Is this a legal classification tool?', answer: 'RISCK COMPLY supports structured readiness and risk workflows. It does not replace qualified legal assessment or guarantee a regulatory classification.' },
      { question: 'Can assessments be revisited?', answer: 'Yes. Assessments should be reviewed when the system, use case, provider, data or legal context changes.' },
      { question: 'Who should participate in an assessment?', answer: 'Depending on the use case, participants may include product, engineering, security, privacy, legal, compliance, procurement and the accountable business owner.' },
    ],
    ctaTitle: 'Make AI risk review repeatable and reviewable',
    ctaText: 'Bring assessment context, decisions, owners and supporting evidence together instead of managing them in disconnected documents.',
  },
  'evidence-management': {
    key: 'evidence-management',
    slug: 'evidence-management',
    navLabel: 'Evidence management',
    title: 'AI Compliance Evidence Management Software',
    description: 'Organize AI governance evidence, documents, decisions, owners and review status into structured evidence packs for internal and external review.',
    eyebrow: 'Compliance evidence management',
    intro: 'Prepare evidence as an operating discipline, not a last-minute document hunt. RISCK COMPLY connects records, decisions and supporting files to the systems and controls they support.',
    problemTitle: 'Evidence loses value when nobody knows what it proves',
    problem: 'Files stored in generic folders rarely show which system, control, decision or owner they relate to. Structured evidence management preserves context and makes review faster.',
    capabilitiesTitle: 'Build evidence packs with clear context',
    capabilities: [
      'Link documents and records to systems, assessments and controls',
      'Track evidence owners, review state, dates and missing items',
      'Record decisions and supporting rationale alongside attachments',
      'Prepare bounded packs for legal, security, procurement or audit review',
    ],
    workflowTitle: 'From evidence request to review-ready pack',
    workflow: ['Define the evidence requirement', 'Assign an owner and due date', 'Attach or generate the supporting record', 'Review completeness and preserve activity history'],
    faqTitle: 'Evidence management questions',
    faq: [
      { question: 'What belongs in an AI governance evidence pack?', answer: 'The contents depend on the system and review scope, but may include inventory records, assessments, policies, approvals, provider information, testing records and monitoring evidence.' },
      { question: 'Does storing a document prove a control is effective?', answer: 'No. Evidence must be relevant, current and connected to the control or decision it is intended to support.' },
      { question: 'Can evidence be organized by AI system?', answer: 'Yes. The platform is designed to connect evidence to organization-scoped systems, reviews, owners and governance activities.' },
    ],
    ctaTitle: 'Turn scattered files into reviewable governance evidence',
    ctaText: 'Organize evidence by system, owner, requirement and review status so teams can understand what exists and what is still missing.',
  },
  'ai-governance-workflows': {
    key: 'ai-governance-workflows',
    slug: 'ai-governance-workflows',
    navLabel: 'Governance workflows',
    title: 'AI Governance Workflow Software for Cross-Functional Teams',
    description: 'Coordinate AI intake, ownership, reviews, approvals, evidence and monitoring across product, legal, security, privacy and compliance teams.',
    eyebrow: 'AI governance workflows',
    intro: 'Give every AI system a clear operating path from discovery to ongoing review. Coordinate responsibilities without turning governance into a chain of spreadsheets and email threads.',
    problemTitle: 'Governance stalls when work has no owner or next step',
    problem: 'AI governance is cross-functional. Without visible responsibilities, review status and escalation paths, important work can remain unresolved even when policies exist.',
    capabilitiesTitle: 'Coordinate governance work in one place',
    capabilities: [
      'Structured intake and ownership assignment',
      'Review stages, tasks, due dates and approval checkpoints',
      'Evidence requests connected to systems and assessments',
      'Monitoring, change review and traceable activity history',
    ],
    workflowTitle: 'A shared operating flow',
    workflow: ['Discover and register the AI use case', 'Assign accountable owners and reviewers', 'Assess risk and collect evidence', 'Approve, document and monitor changes'],
    faqTitle: 'Governance workflow questions',
    faq: [
      { question: 'Which teams can use the workflow?', answer: 'Common participants include product, engineering, legal, compliance, privacy, security, procurement and business owners.' },
      { question: 'Can the workflow replace internal policies?', answer: 'No. Workflows help teams execute and evidence governance processes; policies and legal requirements still need appropriate ownership and review.' },
      { question: 'Why connect tasks to AI systems?', answer: 'System-linked tasks preserve context, reduce ambiguity and make it easier to understand why an action exists and who is responsible.' },
    ],
    ctaTitle: 'Operate AI governance as a real business process',
    ctaText: 'Create visible ownership, consistent review stages and traceable follow-up across every AI system.',
  },
  'vendor-ai-risk': {
    key: 'vendor-ai-risk',
    slug: 'vendor-ai-risk',
    navLabel: 'Vendor AI risk',
    title: 'AI Vendor Risk and Provider Assurance Workflows',
    description: 'Track AI providers, services, contracts, data context, evidence requests and review decisions for procurement and third-party risk workflows.',
    eyebrow: 'AI vendor risk',
    intro: 'Understand which providers support each AI use case and what evidence is available before procurement, deployment or renewal decisions are made.',
    problemTitle: 'Provider risk cannot be reviewed separately from the use case',
    problem: 'The same AI service may create different risks depending on the data, users, integrations and business process involved. Vendor review needs both provider evidence and system context.',
    capabilitiesTitle: 'Connect provider review to operational use',
    capabilities: [
      'Provider profile, services, regions and linked AI systems',
      'Security, privacy, contractual and governance evidence requests',
      'Review owners, findings, decisions and remediation actions',
      'Renewal, material change and dependency monitoring context',
    ],
    workflowTitle: 'A structured provider review',
    workflow: ['Register the provider and linked use case', 'Request relevant assurance evidence', 'Review findings with accountable stakeholders', 'Record decisions, conditions and follow-up actions'],
    faqTitle: 'AI vendor risk questions',
    faq: [
      { question: 'Is vendor review the same as AI system assessment?', answer: 'No. Provider assurance examines the third party and service, while system assessment considers the organization’s specific use case, impact and controls. The two should be connected.' },
      { question: 'What evidence can be requested from providers?', answer: 'Requests may include security documentation, data-processing terms, model or service information, incident processes, contractual commitments and other context relevant to the use case.' },
      { question: 'Can a provider be linked to multiple systems?', answer: 'Yes. One provider may support several systems or business processes, each with different owners and risk context.' },
    ],
    ctaTitle: 'Make AI provider review easier to operate',
    ctaText: 'Connect vendors, systems, evidence requests and decisions so procurement and governance teams work from the same context.',
  },
  'eu-ai-act-readiness': {
    key: 'eu-ai-act-readiness',
    slug: 'eu-ai-act-readiness',
    navLabel: 'EU AI Act readiness',
    title: 'EU AI Act Readiness Platform for European B2B Teams',
    description: 'Organize AI systems, responsibilities, risk context, governance documents and evidence to support practical EU AI Act readiness work.',
    eyebrow: 'EU AI Act readiness',
    intro: 'Build the operational records your team needs to understand AI use, coordinate responsibilities and prepare evidence for legal and compliance review.',
    problemTitle: 'Readiness requires more than a one-time checklist',
    problem: 'AI systems, providers, use cases and legal interpretations change. Teams need an operating model that keeps inventory, decisions, evidence and follow-up work connected over time.',
    capabilitiesTitle: 'Support readiness across the governance lifecycle',
    capabilities: [
      'AI inventory and role ownership',
      'Risk signals, assessments and review rationale',
      'Policies, evidence packs and provider documentation',
      'Tasks, approvals, monitoring and activity history',
    ],
    workflowTitle: 'Move from visibility to evidence preparation',
    workflow: ['Identify systems and organizational roles', 'Assess use cases and relevant obligations', 'Prepare documentation and supporting evidence', 'Review changes, gaps and ongoing actions'],
    faqTitle: 'EU AI Act readiness questions',
    faq: [
      { question: 'Does RISCK COMPLY provide legal advice?', answer: 'No. The platform supports governance operations and evidence preparation. Organizations should obtain qualified legal advice for their specific obligations.' },
      { question: 'Does using the platform make a company compliant?', answer: 'No software can guarantee compliance outcomes. Readiness depends on the organization, systems, controls, evidence, decisions and applicable legal interpretation.' },
      { question: 'Which European teams can use the platform?', answer: 'RISCK COMPLY is designed for cross-functional B2B teams working on AI governance, including compliance, legal, security, privacy, product, engineering and procurement.' },
    ],
    ctaTitle: 'Build an operating foundation for AI Act readiness',
    ctaText: 'Organize the systems, owners, risks, documents and evidence your team needs to review AI governance work clearly.',
  },
  'audit-trails': {
    key: 'audit-trails',
    slug: 'ai-governance-audit-trails',
    navLabel: 'Audit trails',
    title: 'AI Governance Audit Trails and Activity History',
    description: 'Keep AI governance actions, changes, decisions and evidence activity traceable for internal review, investigations and procurement diligence.',
    eyebrow: 'Governance activity history',
    intro: 'Preserve the context behind important governance activity. Review who changed records, what decision was made and which evidence supported the work.',
    problemTitle: 'A final document rarely explains how the decision was reached',
    problem: 'Reviewers often need the sequence of actions, ownership changes, approvals and evidence updates behind a result. Traceable activity helps teams reconstruct that context.',
    capabilitiesTitle: 'Keep governance activity reviewable',
    capabilities: [
      'System, assessment and evidence change history',
      'Ownership, task and approval activity',
      'Security- and compliance-relevant event context',
      'Bounded records for review and investigation support',
    ],
    workflowTitle: 'Use activity history during review',
    workflow: ['Identify the system or governance record', 'Review relevant events and responsible users', 'Connect changes to decisions and evidence', 'Record follow-up or corrective actions'],
    faqTitle: 'Audit trail questions',
    faq: [
      { question: 'Are activity logs legally immutable?', answer: 'RISCK COMPLY does not claim external immutability unless separate technical evidence supports that statement. Activity history is designed for traceability and review.' },
      { question: 'Why are audit trails useful for governance?', answer: 'They help teams understand changes, responsibilities and decision context, which supports internal review, incident analysis and procurement diligence.' },
      { question: 'Do audit trails replace formal audit evidence?', answer: 'No. They can support an evidence package, but the required proof depends on the scope and reviewer.' },
    ],
    ctaTitle: 'Keep AI governance decisions traceable',
    ctaText: 'Preserve activity context across systems, assessments, evidence and follow-up work.',
  },
  'compliance-documentation': {
    key: 'compliance-documentation',
    slug: 'ai-compliance-documentation',
    navLabel: 'Compliance documentation',
    title: 'AI Governance and Compliance Documentation Software',
    description: 'Prepare, organize and maintain AI governance policies, records, reports and supporting documentation with clear ownership and review status.',
    eyebrow: 'AI compliance documentation',
    intro: 'Create documentation that stays connected to the systems, decisions and evidence it describes. Keep owners and review dates visible as governance work changes.',
    problemTitle: 'Documentation becomes stale when it is separated from operations',
    problem: 'Policies and reports are easier to maintain when they are linked to current systems, assessments, owners and evidence rather than copied between isolated files.',
    capabilitiesTitle: 'Maintain governance documentation with context',
    capabilities: [
      'Policies, reports, registers and review-ready summaries',
      'Document ownership, status, version and review dates',
      'Links to systems, assessments, evidence and decisions',
      'Controlled preparation for internal, legal or procurement review',
    ],
    workflowTitle: 'A maintainable documentation process',
    workflow: ['Select the document purpose and scope', 'Connect relevant systems, owners and evidence', 'Prepare and review the content', 'Approve, publish and schedule future review'],
    faqTitle: 'Documentation questions',
    faq: [
      { question: 'Can generated documents replace legal review?', answer: 'No. Generated or templated material should be reviewed by appropriate legal, compliance and subject-matter owners before it is relied upon.' },
      { question: 'Why link documents to systems?', answer: 'The link makes scope clearer and helps teams update documentation when a system, use case, provider or assessment changes.' },
      { question: 'What types of documents can be organized?', answer: 'Examples may include AI policies, inventories, assessment summaries, governance reports, provider records and evidence-pack documentation.' },
    ],
    ctaTitle: 'Keep AI governance documentation connected to real work',
    ctaText: 'Prepare and maintain documents with visible ownership, supporting evidence and review status.',
  },
};
