import type { LocalizedFeaturePages } from './types';

export const esFeaturePages: LocalizedFeaturePages = {
  'ai-inventory': {
    key: 'ai-inventory',
    slug: 'inventario-de-ia',
    navLabel: 'Inventario de IA',
    title: 'Software de Inventario de Sistemas de IA para Equipos Europeos',
    description: 'Crea un inventario estructurado de sistemas de IA, casos de uso, responsables, proveedores, países, contexto de datos y estado de revisión.',
    eyebrow: 'Inventario de sistemas de IA',
    intro: 'Construye un registro fiable de los sistemas de IA que tu organización utiliza, compra, desarrolla u opera. RISCK COMPLY ayuda a sustituir hojas de cálculo dispersas por registros responsables y revisables.',
    problemTitle: 'Evita perder la responsabilidad sobre la IA entre hojas de cálculo y correos',
    problem: 'La gobernanza se complica cuando sistemas, responsables, proveedores y evidencias viven en herramientas separadas. Un inventario estructurado crea la base operativa para evaluar riesgos, documentar y monitorizar.',
    capabilitiesTitle: 'Qué puede organizar el inventario de IA',
    capabilities: ['Nombre, finalidad, departamento, responsable y estado del ciclo de vida', 'Proveedor, modelo de despliegue, países y procesos afectados', 'Categorías de datos, usuarios, integraciones y documentación', 'Señales de riesgo, estado de evaluación, brechas de evidencia y acciones'],
    workflowTitle: 'Un flujo práctico de inventario',
    workflow: ['Registrar el sistema y el caso de uso', 'Asignar responsables y revisores', 'Capturar contexto de proveedor, datos y despliegue', 'Conectar evaluaciones, evidencias, tareas y seguimiento'],
    faqTitle: 'Preguntas sobre inventario de IA',
    faq: [
      { question: '¿Qué es un inventario de sistemas de IA?', answer: 'Es un registro estructurado de los sistemas que una organización desarrolla, adquiere o utiliza, con finalidad, responsables, proveedores, contexto de riesgo y evidencias.' },
      { question: '¿Un inventario garantiza el cumplimiento del AI Act?', answer: 'No. Apoya la gobernanza y la preparación de evidencias, pero las obligaciones dependen de la organización, su papel, el sistema y la normativa aplicable.' },
      { question: '¿Se pueden migrar registros desde hojas de cálculo?', answer: 'RISCK COMPLY está diseñada para apoyar una incorporación estructurada de registros existentes preservando responsables y contexto de revisión.' },
    ],
    ctaTitle: 'Crea una fuente operativa única para los sistemas de IA',
    ctaText: 'Organiza sistemas, responsables, riesgos y evidencias en un workspace controlado para equipos B2B europeos.',
  },
  'ai-risk-assessment': {
    key: 'ai-risk-assessment',
    slug: 'evaluacion-de-riesgos-de-ia',
    navLabel: 'Evaluación de riesgos de IA',
    title: 'Software de Evaluación de Riesgos de IA y Flujos de Revisión',
    description: 'Registra señales de riesgo, contexto, decisiones, responsables y acciones con flujos trazables para equipos B2B europeos.',
    eyebrow: 'Evaluación de riesgos de IA',
    intro: 'Convierte la revisión de riesgos en un proceso repetible. Recopila contexto, implica a las personas adecuadas y vincula las decisiones con los sistemas y evidencias correspondientes.',
    problemTitle: 'Las decisiones de riesgo necesitan contexto, responsabilidad y trazabilidad',
    problem: 'Una etiqueta de riesgo no es suficiente. Los equipos deben comprender el caso de uso, las personas afectadas, los datos, el nivel de automatización, los proveedores y los controles detrás de cada conclusión.',
    capabilitiesTitle: 'Estructura todo el contexto de la revisión',
    capabilities: ['Señales relacionadas con uso, impacto, datos, usuarios y despliegue', 'Clasificación inicial, estado de revisión y justificación documentada', 'Responsables, tareas de mitigación y puntos de aprobación', 'Evidencias, políticas, proveedores e historial vinculados'],
    workflowTitle: 'De la recopilación a la decisión revisada',
    workflow: ['Recopilar contexto del sistema y caso de uso', 'Registrar señales de riesgo relevantes', 'Asignar revisores y solicitudes de evidencia', 'Documentar conclusiones, acciones y monitorización'],
    faqTitle: 'Preguntas sobre evaluación de riesgos',
    faq: [
      { question: '¿Es una herramienta de clasificación jurídica automática?', answer: 'No. RISCK COMPLY apoya flujos estructurados de readiness y riesgo, pero no sustituye una evaluación jurídica cualificada ni garantiza una clasificación regulatoria.' },
      { question: '¿Las evaluaciones pueden revisarse?', answer: 'Sí. Deben revisarse cuando cambian el sistema, el caso de uso, el proveedor, los datos o el contexto jurídico.' },
      { question: '¿Quién debe participar?', answer: 'Según el caso, producto, ingeniería, seguridad, privacidad, legal, compliance, compras y el responsable de negocio.' },
    ],
    ctaTitle: 'Haz que la revisión de riesgos sea repetible y revisable',
    ctaText: 'Reúne contexto, decisiones, responsables y evidencias en lugar de gestionarlos en documentos desconectados.',
  },
  'evidence-management': {
    key: 'evidence-management',
    slug: 'gestion-de-evidencias',
    navLabel: 'Gestión de evidencias',
    title: 'Software de Gestión de Evidencias para Compliance de IA',
    description: 'Organiza evidencias de gobernanza de IA, documentos, decisiones, responsables y estado de revisión en paquetes estructurados.',
    eyebrow: 'Gestión de evidencias de compliance',
    intro: 'Prepara evidencias como una disciplina operativa, no como una búsqueda de archivos de última hora. RISCK COMPLY conecta registros, decisiones y documentos con los sistemas y controles que respaldan.',
    problemTitle: 'La evidencia pierde valor cuando nadie sabe qué demuestra',
    problem: 'Los archivos en carpetas genéricas rara vez muestran a qué sistema, control, decisión o responsable pertenecen. La gestión estructurada conserva el contexto y acelera la revisión.',
    capabilitiesTitle: 'Crea paquetes de evidencia con contexto claro',
    capabilities: ['Vincular documentos con sistemas, evaluaciones y controles', 'Controlar responsables, estado, fechas y elementos pendientes', 'Registrar decisiones y justificación junto a los anexos', 'Preparar paquetes delimitados para legal, seguridad, compras o auditoría'],
    workflowTitle: 'De la solicitud al paquete listo para revisión',
    workflow: ['Definir el requisito de evidencia', 'Asignar responsable y fecha', 'Adjuntar o preparar el registro de soporte', 'Revisar completitud y conservar el historial'],
    faqTitle: 'Preguntas sobre gestión de evidencias',
    faq: [
      { question: '¿Qué puede incluir un paquete de evidencia de IA?', answer: 'Según el sistema y el alcance, inventarios, evaluaciones, políticas, aprobaciones, información de proveedores, pruebas y evidencias de seguimiento.' },
      { question: '¿Guardar un documento demuestra que un control funciona?', answer: 'No. La evidencia debe ser relevante, actual y estar vinculada al control o decisión que pretende respaldar.' },
      { question: '¿Puede organizarse por sistema de IA?', answer: 'Sí. La plataforma conecta evidencias con sistemas, revisiones, responsables y actividades dentro de la organización.' },
    ],
    ctaTitle: 'Convierte archivos dispersos en evidencia revisable',
    ctaText: 'Organiza evidencias por sistema, responsable, requisito y estado para saber qué existe y qué falta.',
  },
  'ai-governance-workflows': {
    key: 'ai-governance-workflows',
    slug: 'flujos-de-gobernanza-de-ia',
    navLabel: 'Flujos de gobernanza',
    title: 'Software de Flujos de Gobernanza de IA para Equipos Multidisciplinares',
    description: 'Coordina intake, responsables, evaluaciones, aprobaciones, evidencias y seguimiento entre producto, legal, seguridad, privacidad y compliance.',
    eyebrow: 'Flujos de gobernanza de IA',
    intro: 'Da a cada sistema de IA un recorrido claro desde el descubrimiento hasta la revisión continua. Coordina responsabilidades sin convertir la gobernanza en una cadena de hojas de cálculo y correos.',
    problemTitle: 'La gobernanza se bloquea cuando no hay responsable ni siguiente paso',
    problem: 'La gobernanza de IA es multidisciplinar. Sin responsabilidades, estados de revisión y escalados visibles, el trabajo puede quedar pendiente aunque existan políticas.',
    capabilitiesTitle: 'Coordina el trabajo de gobernanza en un solo lugar',
    capabilities: ['Intake estructurado y asignación de responsables', 'Etapas de revisión, tareas, fechas y aprobaciones', 'Solicitudes de evidencia vinculadas a sistemas y evaluaciones', 'Seguimiento, revisión de cambios e historial trazable'],
    workflowTitle: 'Un flujo operativo compartido',
    workflow: ['Descubrir y registrar el caso de uso', 'Asignar responsables y revisores', 'Evaluar riesgos y recopilar evidencia', 'Aprobar, documentar y monitorizar cambios'],
    faqTitle: 'Preguntas sobre flujos de gobernanza',
    faq: [
      { question: '¿Qué equipos pueden participar?', answer: 'Producto, ingeniería, legal, compliance, privacidad, seguridad, compras y responsables de negocio.' },
      { question: '¿El flujo sustituye las políticas internas?', answer: 'No. Ayuda a ejecutar y evidenciar procesos; las políticas y obligaciones siguen necesitando responsables y revisión adecuada.' },
      { question: '¿Por qué vincular tareas a sistemas de IA?', answer: 'La vinculación conserva contexto, reduce ambigüedad y aclara por qué existe una acción y quién responde por ella.' },
    ],
    ctaTitle: 'Opera la gobernanza de IA como un proceso real',
    ctaText: 'Crea responsabilidad visible, etapas coherentes y seguimiento trazable para cada sistema de IA.',
  },
  'vendor-ai-risk': {
    key: 'vendor-ai-risk',
    slug: 'riesgo-de-proveedores-de-ia',
    navLabel: 'Riesgo de proveedores de IA',
    title: 'Flujos de Riesgo de Proveedores de IA y Assurance de Terceros',
    description: 'Controla proveedores de IA, servicios, contratos, contexto de datos, solicitudes de evidencia y decisiones de compras y third-party risk.',
    eyebrow: 'Riesgo de proveedores de IA',
    intro: 'Comprende qué proveedores respaldan cada caso de uso y qué evidencias existen antes de decisiones de compra, despliegue o renovación.',
    problemTitle: 'El riesgo del proveedor no puede revisarse sin el contexto de uso',
    problem: 'Un mismo servicio puede crear riesgos distintos según los datos, usuarios, integraciones y procesos. La revisión necesita evidencia del proveedor y contexto del sistema.',
    capabilitiesTitle: 'Conecta la revisión del proveedor con el uso operativo',
    capabilities: ['Perfil, servicios, regiones y sistemas vinculados', 'Solicitudes de evidencia de seguridad, privacidad, contratos y gobernanza', 'Responsables, hallazgos, decisiones y acciones', 'Contexto de renovación, cambios materiales y dependencias'],
    workflowTitle: 'Una revisión estructurada del proveedor',
    workflow: ['Registrar proveedor y caso de uso', 'Solicitar evidencias relevantes', 'Revisar hallazgos con responsables', 'Documentar decisiones, condiciones y acciones'],
    faqTitle: 'Preguntas sobre riesgo de proveedores',
    faq: [
      { question: '¿La revisión del proveedor es igual a la evaluación del sistema?', answer: 'No. La assurance examina al tercero y el servicio; la evaluación del sistema considera el caso de uso, impacto y controles de la organización. Deben conectarse.' },
      { question: '¿Qué evidencias pueden solicitarse?', answer: 'Documentación de seguridad, términos de tratamiento, información del servicio o modelo, procesos de incidentes y compromisos contractuales.' },
      { question: '¿Un proveedor puede vincularse a varios sistemas?', answer: 'Sí. Puede respaldar varios sistemas o procesos, cada uno con responsables y contexto de riesgo diferentes.' },
    ],
    ctaTitle: 'Haz más operativa la revisión de proveedores de IA',
    ctaText: 'Conecta proveedores, sistemas, evidencias y decisiones para que compras y gobernanza trabajen con el mismo contexto.',
  },
  'eu-ai-act-readiness': {
    key: 'eu-ai-act-readiness',
    slug: 'preparacion-para-el-ai-act',
    navLabel: 'Preparación para el AI Act',
    title: 'Plataforma de Preparación para el EU AI Act para Equipos B2B Europeos',
    description: 'Organiza sistemas, responsabilidades, contexto de riesgo, documentación y evidencias para apoyar la preparación práctica ante el EU AI Act.',
    eyebrow: 'Preparación para el EU AI Act',
    intro: 'Construye los registros operativos necesarios para entender el uso de IA, coordinar responsabilidades y preparar evidencias para revisión legal y de compliance.',
    problemTitle: 'La preparación requiere más que una checklist puntual',
    problem: 'Los sistemas, proveedores, casos de uso e interpretaciones cambian. Los equipos necesitan un modelo operativo que mantenga conectados inventario, decisiones, evidencias y acciones.',
    capabilitiesTitle: 'Apoya la preparación durante todo el ciclo',
    capabilities: ['Inventario de IA y asignación de responsabilidades', 'Señales de riesgo, evaluaciones y justificación', 'Políticas, paquetes de evidencia y documentación de proveedores', 'Tareas, aprobaciones, seguimiento e historial'],
    workflowTitle: 'De la visibilidad a la preparación de evidencias',
    workflow: ['Identificar sistemas y roles', 'Evaluar casos de uso y obligaciones relevantes', 'Preparar documentación y evidencias', 'Revisar cambios, brechas y acciones continuas'],
    faqTitle: 'Preguntas sobre preparación para el EU AI Act',
    faq: [
      { question: '¿RISCK COMPLY ofrece asesoramiento jurídico?', answer: 'No. La plataforma apoya operaciones de gobernanza y preparación de evidencias. La organización debe obtener asesoramiento cualificado para sus obligaciones.' },
      { question: '¿Usar la plataforma hace que una empresa cumpla?', answer: 'No. Ningún software garantiza resultados de cumplimiento. Depende de la organización, sistemas, controles, evidencias, decisiones e interpretación aplicable.' },
      { question: '¿Qué equipos pueden utilizarla?', answer: 'Equipos B2B de compliance, legal, seguridad, privacidad, producto, ingeniería, compras y gobernanza de IA.' },
    ],
    ctaTitle: 'Construye una base operativa para el AI Act',
    ctaText: 'Organiza sistemas, responsables, riesgos, documentos y evidencias para revisar claramente el trabajo de gobernanza.',
  },
  'audit-trails': {
    key: 'audit-trails',
    slug: 'registros-de-auditoria-de-ia',
    navLabel: 'Registros de auditoría',
    title: 'Registros de Auditoría e Historial de Gobernanza de IA',
    description: 'Mantén acciones, cambios, decisiones y evidencias trazables para revisión interna, investigación y diligencia de compras.',
    eyebrow: 'Historial de actividad de gobernanza',
    intro: 'Conserva el contexto de la actividad de gobernanza. Revisa quién cambió registros, qué decisión se tomó y qué evidencias respaldaron el trabajo.',
    problemTitle: 'Un documento final rara vez explica cómo se llegó a la decisión',
    problem: 'Los revisores pueden necesitar la secuencia de acciones, cambios de responsabilidad, aprobaciones y actualizaciones. Un historial trazable permite reconstruir el contexto.',
    capabilitiesTitle: 'Mantén la actividad preparada para revisión',
    capabilities: ['Historial de sistemas, evaluaciones y evidencias', 'Actividad de responsables, tareas y aprobaciones', 'Contexto de eventos relevantes de seguridad y compliance', 'Registros delimitados para revisión e investigación'],
    workflowTitle: 'Utiliza el historial durante una revisión',
    workflow: ['Identificar el sistema o registro', 'Revisar eventos y usuarios responsables', 'Conectar cambios con decisiones y evidencias', 'Registrar acciones correctivas o de seguimiento'],
    faqTitle: 'Preguntas sobre registros de auditoría',
    faq: [
      { question: '¿Los registros son jurídicamente inmutables?', answer: 'RISCK COMPLY no afirma inmutabilidad externa sin evidencia técnica separada. El historial está diseñado para trazabilidad y revisión.' },
      { question: '¿Por qué son útiles?', answer: 'Ayudan a comprender cambios, responsabilidades y decisiones, apoyando revisión interna, análisis de incidentes y compras.' },
      { question: '¿Sustituyen evidencias formales de auditoría?', answer: 'No. Pueden apoyar un paquete, pero la prueba necesaria depende del alcance y del revisor.' },
    ],
    ctaTitle: 'Mantén trazables las decisiones de gobernanza',
    ctaText: 'Conserva el contexto entre sistemas, evaluaciones, evidencias y acciones.',
  },
  'compliance-documentation': {
    key: 'compliance-documentation',
    slug: 'documentacion-de-compliance-de-ia',
    navLabel: 'Documentación de compliance',
    title: 'Software de Documentación de Gobernanza y Compliance de IA',
    description: 'Prepara, organiza y mantiene políticas, registros, informes y documentación de IA con responsables y estado de revisión claros.',
    eyebrow: 'Documentación de compliance de IA',
    intro: 'Crea documentación conectada con los sistemas, decisiones y evidencias que describe. Mantén visibles responsables y fechas de revisión.',
    problemTitle: 'La documentación queda obsoleta cuando se separa de las operaciones',
    problem: 'Las políticas e informes se mantienen mejor cuando están vinculados a sistemas, evaluaciones, responsables y evidencias actuales, en lugar de copiarse entre archivos aislados.',
    capabilitiesTitle: 'Mantén documentación con contexto operativo',
    capabilities: ['Políticas, informes, registros y resúmenes revisables', 'Responsable, estado, versión y fechas de revisión', 'Vínculos con sistemas, evaluaciones, evidencias y decisiones', 'Preparación controlada para revisión interna, legal o de compras'],
    workflowTitle: 'Un proceso de documentación sostenible',
    workflow: ['Seleccionar finalidad y alcance', 'Conectar sistemas, responsables y evidencias', 'Preparar y revisar contenido', 'Aprobar, publicar y programar la siguiente revisión'],
    faqTitle: 'Preguntas sobre documentación',
    faq: [
      { question: '¿Los documentos generados sustituyen la revisión jurídica?', answer: 'No. Los materiales generados o basados en plantillas deben revisarse por responsables jurídicos, de compliance y especialistas adecuados.' },
      { question: '¿Por qué vincular documentos a sistemas?', answer: 'Aclara el alcance y ayuda a actualizar la documentación cuando cambia el sistema, caso de uso, proveedor o evaluación.' },
      { question: '¿Qué documentos pueden organizarse?', answer: 'Políticas de IA, inventarios, resúmenes de evaluación, informes, registros de proveedores y documentación de paquetes de evidencia.' },
    ],
    ctaTitle: 'Mantén la documentación conectada con el trabajo real',
    ctaText: 'Prepara y mantiene documentos con responsabilidad, evidencias de soporte y estado de revisión visibles.',
  },
};
