import type { LocalizedFeaturePages } from './types';

export const frFeaturePages: LocalizedFeaturePages = {
  'ai-inventory': {
    key: 'ai-inventory',
    slug: 'inventaire-ia',
    navLabel: 'Inventaire IA',
    title: 'Logiciel d’Inventaire des Systèmes d’IA pour les Équipes Européennes',
    description: 'Créez un inventaire structuré des systèmes d’IA, cas d’usage, responsables, fournisseurs, pays, données et statut de revue.',
    eyebrow: 'Inventaire des systèmes d’IA',
    intro: 'Construisez un registre fiable des systèmes d’IA que votre organisation utilise, achète, développe ou exploite. RISCK COMPLY remplace les feuilles de calcul dispersées par des dossiers responsables et révisables.',
    problemTitle: 'Ne perdez plus la responsabilité de l’IA entre tableurs et emails',
    problem: 'La gouvernance devient difficile lorsque systèmes, responsables, fournisseurs et preuves sont répartis dans plusieurs outils. Un inventaire structuré fournit la base opérationnelle pour l’évaluation, la documentation et le suivi.',
    capabilitiesTitle: 'Ce que l’inventaire IA peut organiser',
    capabilities: ['Nom, finalité, département, responsable et cycle de vie', 'Fournisseur, déploiement, pays et processus concernés', 'Catégories de données, utilisateurs, intégrations et documents', 'Signaux de risque, statut d’évaluation, preuves manquantes et actions'],
    workflowTitle: 'Un flux d’inventaire pratique',
    workflow: ['Enregistrer le système et le cas d’usage', 'Attribuer responsables et réviseurs', 'Documenter fournisseur, données et déploiement', 'Relier évaluations, preuves, tâches et suivi'],
    faqTitle: 'Questions sur l’inventaire IA',
    faq: [
      { question: 'Qu’est-ce qu’un inventaire des systèmes d’IA ?', answer: 'Un registre structuré des systèmes qu’une organisation développe, achète ou utilise, avec finalité, responsables, fournisseurs, contexte de risque et preuves.' },
      { question: 'Un inventaire garantit-il la conformité au AI Act ?', answer: 'Non. Il soutient la gouvernance et la préparation des preuves, mais les obligations dépendent de l’organisation, de son rôle, du système et du droit applicable.' },
      { question: 'Peut-on migrer des données depuis des tableurs ?', answer: 'RISCK COMPLY est conçue pour faciliter une intégration structurée des dossiers existants tout en conservant responsabilités et contexte de revue.' },
    ],
    ctaTitle: 'Créez une source opérationnelle unique pour vos systèmes d’IA',
    ctaText: 'Organisez systèmes, responsables, risques et preuves dans un workspace contrôlé pour les équipes B2B européennes.',
  },
  'ai-risk-assessment': {
    key: 'ai-risk-assessment',
    slug: 'evaluation-des-risques-ia',
    navLabel: 'Évaluation des risques IA',
    title: 'Logiciel d’Évaluation des Risques IA et Workflows de Revue',
    description: 'Consignez signaux de risque, contexte, décisions, responsables et actions dans des workflows traçables pour équipes B2B européennes.',
    eyebrow: 'Évaluation des risques IA',
    intro: 'Transformez la revue des risques en processus répétable. Recueillez le contexte, impliquez les bons acteurs et reliez les décisions aux systèmes et preuves concernés.',
    problemTitle: 'Les décisions de risque exigent contexte, responsabilité et traçabilité',
    problem: 'Une simple étiquette de risque ne suffit pas. Les équipes doivent comprendre le cas d’usage, les personnes affectées, les données, l’automatisation, les dépendances fournisseurs et les contrôles.',
    capabilitiesTitle: 'Structurez tout le contexte de revue',
    capabilities: ['Signaux liés à l’usage, l’impact, aux données et au déploiement', 'Classification initiale, statut de revue et justification', 'Responsables, actions de remédiation et validations', 'Preuves, politiques, fournisseurs et historique liés'],
    workflowTitle: 'De la collecte à la décision revue',
    workflow: ['Recueillir le contexte du système et du cas d’usage', 'Consigner les signaux de risque', 'Attribuer les réviseurs et demandes de preuve', 'Documenter conclusions, actions et suivi'],
    faqTitle: 'Questions sur l’évaluation des risques',
    faq: [
      { question: 'S’agit-il d’une classification juridique automatique ?', answer: 'Non. RISCK COMPLY soutient des workflows structurés de readiness et de risque, sans remplacer une analyse juridique qualifiée ni garantir une classification.' },
      { question: 'Les évaluations peuvent-elles être révisées ?', answer: 'Oui. Elles doivent être revues lorsque le système, le cas d’usage, le fournisseur, les données ou le contexte juridique changent.' },
      { question: 'Qui doit participer ?', answer: 'Selon le cas : produit, ingénierie, sécurité, confidentialité, juridique, conformité, achats et responsable métier.' },
    ],
    ctaTitle: 'Rendez la revue des risques répétable et révisable',
    ctaText: 'Réunissez contexte, décisions, responsables et preuves au lieu de les gérer dans des documents isolés.',
  },
  'evidence-management': {
    key: 'evidence-management',
    slug: 'gestion-des-preuves',
    navLabel: 'Gestion des preuves',
    title: 'Logiciel de Gestion des Preuves de Conformité IA',
    description: 'Organisez preuves de gouvernance IA, documents, décisions, responsables et statut de revue dans des dossiers structurés.',
    eyebrow: 'Gestion des preuves de conformité',
    intro: 'Préparez les preuves comme une discipline opérationnelle, pas comme une recherche de dernière minute. RISCK COMPLY relie dossiers, décisions et fichiers aux systèmes et contrôles concernés.',
    problemTitle: 'Une preuve perd sa valeur lorsque personne ne sait ce qu’elle démontre',
    problem: 'Les fichiers placés dans des dossiers génériques indiquent rarement le système, le contrôle, la décision ou le responsable concernés. Une gestion structurée conserve le contexte et accélère la revue.',
    capabilitiesTitle: 'Constituez des dossiers de preuves contextualisés',
    capabilities: ['Relier documents aux systèmes, évaluations et contrôles', 'Suivre responsables, statut, dates et éléments manquants', 'Consigner décisions et justification avec les pièces jointes', 'Préparer des dossiers ciblés pour juridique, sécurité, achats ou audit'],
    workflowTitle: 'De la demande au dossier prêt à revoir',
    workflow: ['Définir le besoin de preuve', 'Attribuer un responsable et une échéance', 'Joindre ou préparer le dossier justificatif', 'Vérifier la complétude et conserver l’historique'],
    faqTitle: 'Questions sur la gestion des preuves',
    faq: [
      { question: 'Que peut contenir un dossier de preuves IA ?', answer: 'Selon le système et le périmètre : inventaires, évaluations, politiques, approbations, informations fournisseurs, tests et éléments de suivi.' },
      { question: 'Stocker un document prouve-t-il l’efficacité d’un contrôle ?', answer: 'Non. La preuve doit être pertinente, actuelle et clairement reliée au contrôle ou à la décision qu’elle soutient.' },
      { question: 'Peut-on organiser les preuves par système d’IA ?', answer: 'Oui. La plateforme relie les preuves aux systèmes, revues, responsables et activités de gouvernance de l’organisation.' },
    ],
    ctaTitle: 'Transformez des fichiers dispersés en preuves révisables',
    ctaText: 'Organisez les preuves par système, responsable, exigence et statut pour identifier ce qui existe et ce qui manque.',
  },
  'ai-governance-workflows': {
    key: 'ai-governance-workflows',
    slug: 'workflows-de-gouvernance-ia',
    navLabel: 'Workflows de gouvernance',
    title: 'Logiciel de Workflows de Gouvernance IA pour Équipes Transverses',
    description: 'Coordonnez intake, responsabilités, évaluations, validations, preuves et suivi entre produit, juridique, sécurité, privacy et conformité.',
    eyebrow: 'Workflows de gouvernance IA',
    intro: 'Donnez à chaque système d’IA un parcours clair, de la découverte au suivi continu. Coordonnez les responsabilités sans transformer la gouvernance en chaîne de tableurs et emails.',
    problemTitle: 'La gouvernance se bloque sans responsable ni prochaine étape',
    problem: 'La gouvernance IA est transversale. Sans responsabilités, statuts de revue et escalades visibles, les actions peuvent rester inachevées même lorsque des politiques existent.',
    capabilitiesTitle: 'Coordonnez le travail de gouvernance au même endroit',
    capabilities: ['Intake structuré et attribution des responsabilités', 'Étapes de revue, tâches, échéances et validations', 'Demandes de preuve reliées aux systèmes et évaluations', 'Suivi, revue des changements et historique traçable'],
    workflowTitle: 'Un flux opérationnel partagé',
    workflow: ['Découvrir et enregistrer le cas d’usage', 'Attribuer responsables et réviseurs', 'Évaluer les risques et collecter les preuves', 'Approuver, documenter et suivre les changements'],
    faqTitle: 'Questions sur les workflows de gouvernance',
    faq: [
      { question: 'Quelles équipes peuvent participer ?', answer: 'Produit, ingénierie, juridique, conformité, privacy, sécurité, achats et responsables métier.' },
      { question: 'Le workflow remplace-t-il les politiques internes ?', answer: 'Non. Il aide à exécuter et documenter les processus ; les politiques et obligations nécessitent toujours une gouvernance appropriée.' },
      { question: 'Pourquoi relier les tâches aux systèmes ?', answer: 'Cette liaison conserve le contexte, réduit l’ambiguïté et clarifie la raison de l’action et son responsable.' },
    ],
    ctaTitle: 'Exploitez la gouvernance IA comme un vrai processus métier',
    ctaText: 'Créez des responsabilités visibles, des étapes cohérentes et un suivi traçable pour chaque système.',
  },
  'vendor-ai-risk': {
    key: 'vendor-ai-risk',
    slug: 'risque-fournisseurs-ia',
    navLabel: 'Risque fournisseurs IA',
    title: 'Workflows de Risque Fournisseurs IA et Assurance des Tiers',
    description: 'Suivez fournisseurs IA, services, contrats, contexte des données, demandes de preuve et décisions achats ou third-party risk.',
    eyebrow: 'Risque fournisseurs IA',
    intro: 'Comprenez quels fournisseurs soutiennent chaque cas d’usage et quelles preuves existent avant un achat, un déploiement ou un renouvellement.',
    problemTitle: 'Le risque fournisseur ne peut être évalué sans le contexte d’usage',
    problem: 'Un même service IA peut créer des risques différents selon les données, utilisateurs, intégrations et processus. La revue nécessite preuves du fournisseur et contexte du système.',
    capabilitiesTitle: 'Reliez la revue fournisseur à l’usage opérationnel',
    capabilities: ['Profil, services, régions et systèmes associés', 'Demandes de preuve sécurité, privacy, contractuelles et gouvernance', 'Responsables, constats, décisions et remédiations', 'Contexte de renouvellement, changements matériels et dépendances'],
    workflowTitle: 'Une revue fournisseur structurée',
    workflow: ['Enregistrer le fournisseur et le cas d’usage', 'Demander les preuves pertinentes', 'Revoir les constats avec les responsables', 'Documenter décisions, conditions et actions'],
    faqTitle: 'Questions sur le risque fournisseur',
    faq: [
      { question: 'La revue fournisseur est-elle identique à l’évaluation du système ?', answer: 'Non. L’assurance examine le tiers et le service ; l’évaluation du système considère le cas d’usage, l’impact et les contrôles de l’organisation. Elles doivent être reliées.' },
      { question: 'Quelles preuves demander ?', answer: 'Documentation sécurité, termes de traitement, informations sur le service ou modèle, processus d’incident et engagements contractuels.' },
      { question: 'Un fournisseur peut-il être lié à plusieurs systèmes ?', answer: 'Oui. Il peut soutenir plusieurs systèmes ou processus, chacun avec des responsables et un contexte de risque différents.' },
    ],
    ctaTitle: 'Rendez la revue des fournisseurs IA plus opérationnelle',
    ctaText: 'Reliez fournisseurs, systèmes, demandes de preuve et décisions pour partager le même contexte entre achats et gouvernance.',
  },
  'eu-ai-act-readiness': {
    key: 'eu-ai-act-readiness',
    slug: 'preparation-ai-act',
    navLabel: 'Préparation au AI Act',
    title: 'Plateforme de Préparation au EU AI Act pour les Équipes B2B Européennes',
    description: 'Organisez systèmes IA, responsabilités, contexte de risque, documentation et preuves pour soutenir la préparation pratique au EU AI Act.',
    eyebrow: 'Préparation au EU AI Act',
    intro: 'Construisez les dossiers opérationnels nécessaires pour comprendre l’usage de l’IA, coordonner les responsabilités et préparer les preuves pour revue juridique et conformité.',
    problemTitle: 'La préparation exige plus qu’une checklist ponctuelle',
    problem: 'Systèmes, fournisseurs, cas d’usage et interprétations évoluent. Les équipes ont besoin d’un modèle opérationnel qui relie inventaire, décisions, preuves et actions dans le temps.',
    capabilitiesTitle: 'Soutenez la préparation sur tout le cycle de gouvernance',
    capabilities: ['Inventaire IA et responsabilités', 'Signaux de risque, évaluations et justification', 'Politiques, dossiers de preuves et documents fournisseurs', 'Tâches, validations, suivi et historique'],
    workflowTitle: 'De la visibilité à la préparation des preuves',
    workflow: ['Identifier systèmes et rôles', 'Évaluer cas d’usage et obligations pertinentes', 'Préparer documentation et preuves', 'Revoir changements, écarts et actions continues'],
    faqTitle: 'Questions sur la préparation au EU AI Act',
    faq: [
      { question: 'RISCK COMPLY fournit-elle un conseil juridique ?', answer: 'Non. La plateforme soutient les opérations de gouvernance et la préparation des preuves. L’organisation doit obtenir un conseil qualifié pour ses obligations spécifiques.' },
      { question: 'Utiliser la plateforme garantit-il la conformité ?', answer: 'Non. Aucun logiciel ne garantit un résultat de conformité. Celui-ci dépend de l’organisation, des systèmes, contrôles, preuves, décisions et interprétations applicables.' },
      { question: 'Quelles équipes peuvent l’utiliser ?', answer: 'Les équipes B2B de conformité, juridique, sécurité, privacy, produit, ingénierie, achats et gouvernance IA.' },
    ],
    ctaTitle: 'Construisez une base opérationnelle pour le AI Act',
    ctaText: 'Organisez systèmes, responsables, risques, documents et preuves pour revoir clairement le travail de gouvernance.',
  },
  'audit-trails': {
    key: 'audit-trails',
    slug: 'pistes-audit-ia',
    navLabel: 'Pistes d’audit',
    title: 'Pistes d’Audit et Historique d’Activité de Gouvernance IA',
    description: 'Conservez actions, changements, décisions et preuves traçables pour revue interne, investigation et diligence achats.',
    eyebrow: 'Historique d’activité de gouvernance',
    intro: 'Préservez le contexte des activités de gouvernance. Identifiez qui a modifié un dossier, quelle décision a été prise et quelles preuves l’ont soutenue.',
    problemTitle: 'Un document final explique rarement comment la décision a été prise',
    problem: 'Les réviseurs peuvent avoir besoin de la séquence d’actions, des changements de responsabilité, validations et mises à jour de preuves. Un historique traçable reconstruit ce contexte.',
    capabilitiesTitle: 'Gardez l’activité de gouvernance révisable',
    capabilities: ['Historique des systèmes, évaluations et preuves', 'Activité des responsables, tâches et validations', 'Contexte des événements sécurité et conformité', 'Dossiers ciblés pour revue et investigation'],
    workflowTitle: 'Utilisez l’historique pendant une revue',
    workflow: ['Identifier le système ou dossier', 'Revoir événements et utilisateurs responsables', 'Relier changements, décisions et preuves', 'Consigner actions de suivi ou correctives'],
    faqTitle: 'Questions sur les pistes d’audit',
    faq: [
      { question: 'Les journaux sont-ils juridiquement immuables ?', answer: 'RISCK COMPLY ne revendique pas d’immutabilité externe sans preuve technique distincte. L’historique vise la traçabilité et la revue.' },
      { question: 'Pourquoi sont-ils utiles ?', answer: 'Ils aident à comprendre changements, responsabilités et décisions, pour la revue interne, les incidents et la diligence achats.' },
      { question: 'Remplacent-ils une preuve formelle d’audit ?', answer: 'Non. Ils peuvent soutenir un dossier, mais la preuve requise dépend du périmètre et du réviseur.' },
    ],
    ctaTitle: 'Gardez les décisions de gouvernance IA traçables',
    ctaText: 'Préservez le contexte entre systèmes, évaluations, preuves et actions de suivi.',
  },
  'compliance-documentation': {
    key: 'compliance-documentation',
    slug: 'documentation-conformite-ia',
    navLabel: 'Documentation conformité',
    title: 'Logiciel de Documentation de Gouvernance et Conformité IA',
    description: 'Préparez, organisez et maintenez politiques, registres, rapports et documents IA avec responsabilités et statut de revue clairs.',
    eyebrow: 'Documentation de conformité IA',
    intro: 'Créez une documentation reliée aux systèmes, décisions et preuves qu’elle décrit. Gardez responsables et dates de revue visibles à mesure que les opérations évoluent.',
    problemTitle: 'La documentation devient obsolète lorsqu’elle est séparée des opérations',
    problem: 'Politiques et rapports sont plus faciles à maintenir lorsqu’ils sont reliés aux systèmes, évaluations, responsables et preuves actuels plutôt que copiés entre fichiers isolés.',
    capabilitiesTitle: 'Maintenez la documentation avec son contexte opérationnel',
    capabilities: ['Politiques, rapports, registres et synthèses révisables', 'Responsable, statut, version et dates de revue', 'Liens vers systèmes, évaluations, preuves et décisions', 'Préparation contrôlée pour revue interne, juridique ou achats'],
    workflowTitle: 'Un processus documentaire durable',
    workflow: ['Choisir la finalité et le périmètre', 'Relier systèmes, responsables et preuves', 'Préparer et revoir le contenu', 'Approuver, publier et planifier la prochaine revue'],
    faqTitle: 'Questions sur la documentation',
    faq: [
      { question: 'Les documents générés remplacent-ils la revue juridique ?', answer: 'Non. Les contenus générés ou issus de modèles doivent être revus par les responsables juridiques, conformité et experts compétents.' },
      { question: 'Pourquoi relier les documents aux systèmes ?', answer: 'Cela clarifie le périmètre et facilite les mises à jour lorsque le système, le cas d’usage, le fournisseur ou l’évaluation change.' },
      { question: 'Quels documents peuvent être organisés ?', answer: 'Politiques IA, inventaires, synthèses d’évaluation, rapports, dossiers fournisseurs et documentation de preuves.' },
    ],
    ctaTitle: 'Gardez la documentation reliée au travail réel',
    ctaText: 'Préparez et maintenez les documents avec responsables, preuves et statut de revue visibles.',
  },
};
