import type { LocalizedFeaturePages } from './types';

export const itFeaturePages: LocalizedFeaturePages = {
  'ai-inventory': {
    key: 'ai-inventory',
    slug: 'inventario-ia',
    navLabel: 'Inventario IA',
    title: 'Software di Inventario dei Sistemi di IA per Team Europei',
    description: 'Crea un inventario strutturato di sistemi IA, casi d’uso, responsabili, fornitori, paesi, contesto dati e stato di revisione.',
    eyebrow: 'Inventario dei sistemi di IA',
    intro: 'Costruisci un registro affidabile dei sistemi di IA che la tua organizzazione utilizza, acquista, sviluppa o gestisce. RISCK COMPLY sostituisce fogli di calcolo frammentati con record responsabili e revisionabili.',
    problemTitle: 'Non perdere la responsabilità dell’IA tra fogli di calcolo ed email',
    problem: 'La governance diventa difficile quando sistemi, responsabili, fornitori ed evidenze sono distribuiti in strumenti diversi. Un inventario strutturato crea la base operativa per rischio, documentazione e monitoraggio.',
    capabilitiesTitle: 'Cosa può organizzare l’inventario IA',
    capabilities: ['Nome, finalità, reparto, responsabile e stato del ciclo di vita', 'Fornitore, modello di deployment, paesi e processi coinvolti', 'Categorie di dati, utenti, integrazioni e documentazione', 'Segnali di rischio, stato della valutazione, gap e azioni'],
    workflowTitle: 'Un flusso pratico per l’inventario',
    workflow: ['Registrare sistema e caso d’uso', 'Assegnare responsabili e revisori', 'Raccogliere contesto su fornitore, dati e deployment', 'Collegare valutazioni, evidenze, task e monitoraggio'],
    faqTitle: 'Domande sull’inventario IA',
    faq: [
      { question: 'Cos’è un inventario dei sistemi di IA?', answer: 'È un registro strutturato dei sistemi che un’organizzazione sviluppa, acquista o utilizza, con finalità, responsabili, fornitori, rischio ed evidenze.' },
      { question: 'Un inventario garantisce la conformità all’AI Act?', answer: 'No. Supporta governance e preparazione delle evidenze, ma gli obblighi dipendono dall’organizzazione, dal ruolo, dal sistema e dalla normativa applicabile.' },
      { question: 'Si possono migrare dati da fogli di calcolo?', answer: 'RISCK COMPLY è progettata per supportare l’onboarding strutturato di record esistenti mantenendo responsabilità e contesto di revisione.' },
    ],
    ctaTitle: 'Crea un’unica fonte operativa per i sistemi di IA',
    ctaText: 'Organizza sistemi, responsabili, rischi ed evidenze in un workspace controllato per team B2B europei.',
  },
  'ai-risk-assessment': {
    key: 'ai-risk-assessment',
    slug: 'valutazione-rischio-ia',
    navLabel: 'Valutazione rischio IA',
    title: 'Software di Valutazione del Rischio IA e Workflow di Revisione',
    description: 'Registra segnali di rischio, contesto, decisioni, responsabili e azioni con workflow tracciabili per team B2B europei.',
    eyebrow: 'Valutazione del rischio IA',
    intro: 'Trasforma la revisione del rischio in un processo ripetibile. Raccogli il contesto, coinvolgi le persone giuste e collega le decisioni ai sistemi e alle evidenze rilevanti.',
    problemTitle: 'Le decisioni sul rischio richiedono contesto, responsabilità e tracciabilità',
    problem: 'Una semplice etichetta di rischio non basta. I team devono comprendere caso d’uso, persone interessate, dati, automazione, dipendenze dai fornitori e controlli alla base di ogni conclusione.',
    capabilitiesTitle: 'Struttura l’intero contesto di revisione',
    capabilities: ['Segnali relativi a uso, impatto, dati, utenti e deployment', 'Classificazione iniziale, stato e motivazione documentata', 'Responsabili, azioni di mitigazione e approvazioni', 'Evidenze, policy, fornitori e storico collegati'],
    workflowTitle: 'Dalla raccolta alla decisione revisionata',
    workflow: ['Raccogliere contesto del sistema e caso d’uso', 'Registrare i segnali di rischio', 'Assegnare revisori e richieste di evidenza', 'Documentare conclusioni, azioni e monitoraggio'],
    faqTitle: 'Domande sulla valutazione del rischio',
    faq: [
      { question: 'È uno strumento di classificazione legale automatica?', answer: 'No. RISCK COMPLY supporta workflow strutturati di readiness e rischio, senza sostituire una valutazione legale qualificata o garantire una classificazione.' },
      { question: 'Le valutazioni possono essere riviste?', answer: 'Sì. Devono essere riesaminate quando cambiano sistema, caso d’uso, fornitore, dati o contesto normativo.' },
      { question: 'Chi dovrebbe partecipare?', answer: 'A seconda del caso: prodotto, ingegneria, sicurezza, privacy, legale, compliance, procurement e business owner.' },
    ],
    ctaTitle: 'Rendi la revisione del rischio ripetibile e verificabile',
    ctaText: 'Riunisci contesto, decisioni, responsabili ed evidenze invece di gestirli in documenti scollegati.',
  },
  'evidence-management': {
    key: 'evidence-management',
    slug: 'gestione-evidenze',
    navLabel: 'Gestione evidenze',
    title: 'Software di Gestione delle Evidenze per la Compliance IA',
    description: 'Organizza evidenze di governance IA, documenti, decisioni, responsabili e stato di revisione in pacchetti strutturati.',
    eyebrow: 'Gestione delle evidenze di compliance',
    intro: 'Prepara le evidenze come disciplina operativa, non come ricerca dell’ultimo minuto. RISCK COMPLY collega record, decisioni e file ai sistemi e controlli che supportano.',
    problemTitle: 'Un’evidenza perde valore quando non è chiaro cosa dimostri',
    problem: 'I file in cartelle generiche raramente indicano il sistema, controllo, decisione o responsabile a cui si riferiscono. La gestione strutturata conserva il contesto e accelera la revisione.',
    capabilitiesTitle: 'Costruisci pacchetti di evidenze con contesto chiaro',
    capabilities: ['Collegare documenti a sistemi, valutazioni e controlli', 'Tracciare responsabili, stato, date e elementi mancanti', 'Registrare decisioni e motivazioni con gli allegati', 'Preparare pacchetti delimitati per legale, sicurezza, procurement o audit'],
    workflowTitle: 'Dalla richiesta al pacchetto pronto per la revisione',
    workflow: ['Definire il requisito di evidenza', 'Assegnare responsabile e scadenza', 'Allegare o preparare il record di supporto', 'Verificare completezza e conservare lo storico'],
    faqTitle: 'Domande sulla gestione delle evidenze',
    faq: [
      { question: 'Cosa può includere un pacchetto di evidenze IA?', answer: 'A seconda del sistema e dello scope: inventari, valutazioni, policy, approvazioni, informazioni sui fornitori, test e monitoraggio.' },
      { question: 'Salvare un documento prova l’efficacia di un controllo?', answer: 'No. L’evidenza deve essere pertinente, aggiornata e chiaramente collegata al controllo o alla decisione che intende supportare.' },
      { question: 'Le evidenze possono essere organizzate per sistema?', answer: 'Sì. La piattaforma collega evidenze a sistemi, revisioni, responsabili e attività di governance dell’organizzazione.' },
    ],
    ctaTitle: 'Trasforma file dispersi in evidenze revisionabili',
    ctaText: 'Organizza le evidenze per sistema, responsabile, requisito e stato per capire cosa esiste e cosa manca.',
  },
  'ai-governance-workflows': {
    key: 'ai-governance-workflows',
    slug: 'workflow-governance-ia',
    navLabel: 'Workflow di governance',
    title: 'Software di Workflow di Governance IA per Team Trasversali',
    description: 'Coordina intake, responsabilità, valutazioni, approvazioni, evidenze e monitoraggio tra prodotto, legale, sicurezza, privacy e compliance.',
    eyebrow: 'Workflow di governance IA',
    intro: 'Dai a ogni sistema di IA un percorso chiaro dalla scoperta alla revisione continua. Coordina le responsabilità senza trasformare la governance in una catena di fogli di calcolo ed email.',
    problemTitle: 'La governance si blocca senza responsabile e prossimo passo',
    problem: 'La governance IA è trasversale. Senza responsabilità, stato di revisione ed escalation visibili, il lavoro può restare incompleto anche quando esistono policy.',
    capabilitiesTitle: 'Coordina il lavoro di governance in un solo luogo',
    capabilities: ['Intake strutturato e assegnazione delle responsabilità', 'Fasi di revisione, task, scadenze e approvazioni', 'Richieste di evidenza collegate a sistemi e valutazioni', 'Monitoraggio, revisione dei cambiamenti e storico tracciabile'],
    workflowTitle: 'Un flusso operativo condiviso',
    workflow: ['Scoprire e registrare il caso d’uso', 'Assegnare responsabili e revisori', 'Valutare rischio e raccogliere evidenze', 'Approvare, documentare e monitorare i cambiamenti'],
    faqTitle: 'Domande sui workflow di governance',
    faq: [
      { question: 'Quali team possono partecipare?', answer: 'Prodotto, ingegneria, legale, compliance, privacy, sicurezza, procurement e business owner.' },
      { question: 'Il workflow sostituisce le policy interne?', answer: 'No. Aiuta a eseguire e documentare i processi; policy e obblighi richiedono ancora ownership e revisione adeguate.' },
      { question: 'Perché collegare i task ai sistemi IA?', answer: 'Il collegamento conserva il contesto, riduce l’ambiguità e chiarisce perché esiste un’azione e chi ne è responsabile.' },
    ],
    ctaTitle: 'Gestisci la governance IA come un vero processo aziendale',
    ctaText: 'Crea responsabilità visibili, fasi coerenti e follow-up tracciabile per ogni sistema.',
  },
  'vendor-ai-risk': {
    key: 'vendor-ai-risk',
    slug: 'rischio-fornitori-ia',
    navLabel: 'Rischio fornitori IA',
    title: 'Workflow di Rischio Fornitori IA e Assurance di Terze Parti',
    description: 'Traccia fornitori IA, servizi, contratti, contesto dati, richieste di evidenza e decisioni di procurement o third-party risk.',
    eyebrow: 'Rischio fornitori IA',
    intro: 'Comprendi quali fornitori supportano ogni caso d’uso e quali evidenze sono disponibili prima di acquisto, deployment o rinnovo.',
    problemTitle: 'Il rischio del fornitore non può essere valutato senza il contesto d’uso',
    problem: 'Lo stesso servizio può creare rischi diversi in base a dati, utenti, integrazioni e processi. La revisione richiede evidenze del fornitore e contesto del sistema.',
    capabilitiesTitle: 'Collega la revisione del fornitore all’uso operativo',
    capabilities: ['Profilo, servizi, regioni e sistemi collegati', 'Richieste di evidenza sicurezza, privacy, contratti e governance', 'Responsabili, findings, decisioni e azioni', 'Contesto di rinnovo, cambiamenti materiali e dipendenze'],
    workflowTitle: 'Una revisione strutturata del fornitore',
    workflow: ['Registrare fornitore e caso d’uso', 'Richiedere evidenze rilevanti', 'Rivedere findings con i responsabili', 'Documentare decisioni, condizioni e azioni'],
    faqTitle: 'Domande sul rischio fornitori',
    faq: [
      { question: 'La revisione del fornitore è uguale alla valutazione del sistema?', answer: 'No. L’assurance esamina terza parte e servizio; la valutazione del sistema considera caso d’uso, impatto e controlli dell’organizzazione. Devono essere collegate.' },
      { question: 'Quali evidenze si possono richiedere?', answer: 'Documentazione di sicurezza, termini sul trattamento dati, informazioni sul servizio o modello, processi di incidente e impegni contrattuali.' },
      { question: 'Un fornitore può essere collegato a più sistemi?', answer: 'Sì. Può supportare più sistemi o processi, ciascuno con responsabili e contesto di rischio differenti.' },
    ],
    ctaTitle: 'Rendi più operativa la revisione dei fornitori IA',
    ctaText: 'Collega fornitori, sistemi, richieste di evidenza e decisioni affinché procurement e governance condividano lo stesso contesto.',
  },
  'eu-ai-act-readiness': {
    key: 'eu-ai-act-readiness',
    slug: 'preparazione-ai-act',
    navLabel: 'Preparazione AI Act',
    title: 'Piattaforma di Preparazione al EU AI Act per Team B2B Europei',
    description: 'Organizza sistemi IA, responsabilità, contesto di rischio, documentazione ed evidenze per supportare la preparazione pratica al EU AI Act.',
    eyebrow: 'Preparazione al EU AI Act',
    intro: 'Costruisci i record operativi necessari per comprendere l’uso dell’IA, coordinare responsabilità e preparare evidenze per revisione legale e compliance.',
    problemTitle: 'La preparazione richiede più di una checklist una tantum',
    problem: 'Sistemi, fornitori, casi d’uso e interpretazioni cambiano. I team hanno bisogno di un modello operativo che mantenga collegati inventario, decisioni, evidenze e azioni nel tempo.',
    capabilitiesTitle: 'Supporta la readiness lungo tutto il ciclo di governance',
    capabilities: ['Inventario IA e responsabilità', 'Segnali di rischio, valutazioni e motivazioni', 'Policy, pacchetti di evidenze e documenti fornitori', 'Task, approvazioni, monitoraggio e storico'],
    workflowTitle: 'Dalla visibilità alla preparazione delle evidenze',
    workflow: ['Identificare sistemi e ruoli', 'Valutare casi d’uso e obblighi rilevanti', 'Preparare documentazione ed evidenze', 'Rivedere cambiamenti, gap e azioni continue'],
    faqTitle: 'Domande sulla preparazione al EU AI Act',
    faq: [
      { question: 'RISCK COMPLY fornisce consulenza legale?', answer: 'No. La piattaforma supporta operazioni di governance e preparazione delle evidenze. L’organizzazione deve ottenere consulenza qualificata per i propri obblighi.' },
      { question: 'Usare la piattaforma garantisce la conformità?', answer: 'No. Nessun software garantisce risultati di conformità. Dipendono da organizzazione, sistemi, controlli, evidenze, decisioni e interpretazione applicabile.' },
      { question: 'Quali team possono usarla?', answer: 'Team B2B di compliance, legale, sicurezza, privacy, prodotto, ingegneria, procurement e governance IA.' },
    ],
    ctaTitle: 'Costruisci una base operativa per l’AI Act',
    ctaText: 'Organizza sistemi, responsabili, rischi, documenti ed evidenze per rivedere chiaramente il lavoro di governance.',
  },
  'audit-trails': {
    key: 'audit-trails',
    slug: 'tracce-audit-ia',
    navLabel: 'Tracce di audit',
    title: 'Tracce di Audit e Storico delle Attività di Governance IA',
    description: 'Mantieni azioni, cambiamenti, decisioni ed evidenze tracciabili per revisione interna, indagini e diligence procurement.',
    eyebrow: 'Storico delle attività di governance',
    intro: 'Conserva il contesto delle attività di governance. Verifica chi ha modificato un record, quale decisione è stata presa e quali evidenze l’hanno supportata.',
    problemTitle: 'Un documento finale raramente spiega come si è arrivati alla decisione',
    problem: 'I revisori possono aver bisogno della sequenza di azioni, cambi di responsabilità, approvazioni e aggiornamenti. Uno storico tracciabile ricostruisce il contesto.',
    capabilitiesTitle: 'Mantieni le attività di governance revisionabili',
    capabilities: ['Storico di sistemi, valutazioni ed evidenze', 'Attività di responsabili, task e approvazioni', 'Contesto di eventi sicurezza e compliance', 'Record delimitati per revisione e indagini'],
    workflowTitle: 'Usa lo storico durante una revisione',
    workflow: ['Identificare sistema o record', 'Rivedere eventi e utenti responsabili', 'Collegare cambiamenti, decisioni ed evidenze', 'Registrare azioni correttive o follow-up'],
    faqTitle: 'Domande sulle tracce di audit',
    faq: [
      { question: 'I log sono legalmente immutabili?', answer: 'RISCK COMPLY non dichiara immutabilità esterna senza evidenza tecnica separata. Lo storico è progettato per tracciabilità e revisione.' },
      { question: 'Perché sono utili?', answer: 'Aiutano a comprendere cambiamenti, responsabilità e decisioni, supportando revisione interna, incidenti e diligence procurement.' },
      { question: 'Sostituiscono evidenze formali di audit?', answer: 'No. Possono supportare un pacchetto, ma la prova necessaria dipende dallo scope e dal revisore.' },
    ],
    ctaTitle: 'Mantieni tracciabili le decisioni di governance IA',
    ctaText: 'Conserva il contesto tra sistemi, valutazioni, evidenze e azioni di follow-up.',
  },
  'compliance-documentation': {
    key: 'compliance-documentation',
    slug: 'documentazione-compliance-ia',
    navLabel: 'Documentazione compliance',
    title: 'Software di Documentazione per Governance e Compliance IA',
    description: 'Prepara, organizza e mantieni policy, registri, report e documenti IA con responsabilità e stato di revisione chiari.',
    eyebrow: 'Documentazione di compliance IA',
    intro: 'Crea documentazione collegata ai sistemi, decisioni ed evidenze che descrive. Mantieni visibili responsabili e date di revisione mentre le operazioni evolvono.',
    problemTitle: 'La documentazione diventa obsoleta quando è separata dalle operazioni',
    problem: 'Policy e report sono più facili da mantenere quando collegati a sistemi, valutazioni, responsabili ed evidenze attuali invece di essere copiati tra file isolati.',
    capabilitiesTitle: 'Mantieni la documentazione con contesto operativo',
    capabilities: ['Policy, report, registri e sintesi revisionabili', 'Responsabile, stato, versione e date di revisione', 'Collegamenti a sistemi, valutazioni, evidenze e decisioni', 'Preparazione controllata per revisione interna, legale o procurement'],
    workflowTitle: 'Un processo documentale sostenibile',
    workflow: ['Selezionare finalità e ambito', 'Collegare sistemi, responsabili ed evidenze', 'Preparare e rivedere il contenuto', 'Approvare, pubblicare e programmare la prossima revisione'],
    faqTitle: 'Domande sulla documentazione',
    faq: [
      { question: 'I documenti generati sostituiscono la revisione legale?', answer: 'No. I contenuti generati o basati su template devono essere revisionati da responsabili legali, compliance ed esperti appropriati.' },
      { question: 'Perché collegare i documenti ai sistemi?', answer: 'Chiarisce l’ambito e facilita gli aggiornamenti quando cambiano sistema, caso d’uso, fornitore o valutazione.' },
      { question: 'Quali documenti si possono organizzare?', answer: 'Policy IA, inventari, sintesi di valutazione, report, record fornitori e documentazione dei pacchetti di evidenze.' },
    ],
    ctaTitle: 'Mantieni la documentazione collegata al lavoro reale',
    ctaText: 'Prepara e mantieni documenti con responsabilità, evidenze di supporto e stato di revisione visibili.',
  },
};
