import type { LocalizedFeaturePages } from './types';

export const ptFeaturePages: LocalizedFeaturePages = {
  'ai-inventory': {
    key: 'ai-inventory',
    slug: 'inventario-de-ia',
    navLabel: 'Inventário de IA',
    title: 'Software de Inventário de Sistemas de IA para Equipas Europeias',
    description: 'Crie um inventário estruturado de sistemas de IA, casos de uso, responsáveis, fornecedores, países, contexto de dados e estado de revisão.',
    eyebrow: 'Inventário de sistemas de IA',
    intro: 'Construa um registo fiável dos sistemas de IA que a sua organização utiliza, compra, desenvolve ou opera. A RISCK COMPLY ajuda a substituir folhas de cálculo dispersas por registos responsáveis e preparados para revisão.',
    problemTitle: 'Deixe de perder a responsabilidade sobre IA entre folhas de cálculo e emails',
    problem: 'A governança torna-se difícil quando sistemas, responsáveis, fornecedores e evidências vivem em ferramentas separadas. Um inventário estruturado cria a base operacional para avaliação de risco, documentação e monitorização contínua.',
    capabilitiesTitle: 'O que pode organizar no inventário de IA',
    capabilities: [
      'Nome do sistema, finalidade, departamento, responsável e estado do ciclo de vida',
      'Fornecedor, modelo de implementação, países e processos de negócio afetados',
      'Categorias de dados, utilizadores, integrações e documentação de suporte',
      'Sinais de risco, estado da avaliação, lacunas de evidência e ações de acompanhamento',
    ],
    workflowTitle: 'Um fluxo prático para o inventário',
    workflow: ['Registar o sistema e o caso de uso', 'Atribuir responsáveis e revisores', 'Recolher contexto do fornecedor, dados e implementação', 'Ligar avaliações, evidências, tarefas e monitorização'],
    faqTitle: 'Perguntas sobre inventário de IA',
    faq: [
      { question: 'O que é um inventário de sistemas de IA?', answer: 'É um registo estruturado dos sistemas de IA que uma organização desenvolve, adquire ou utiliza, incluindo finalidade, responsabilidade, fornecedores, contexto de risco e evidências de suporte.' },
      { question: 'Um inventário garante conformidade com o AI Act?', answer: 'Não. O inventário apoia governança e preparação de evidências, mas as obrigações dependem da organização, do papel, do sistema e da legislação aplicável.' },
      { question: 'É possível migrar registos existentes de folhas de cálculo?', answer: 'A RISCK COMPLY foi concebida para apoiar onboarding estruturado e migração de registos existentes, preservando responsáveis e contexto de revisão.' },
    ],
    ctaTitle: 'Crie uma fonte operacional única para os sistemas de IA',
    ctaText: 'Organize sistemas, responsáveis, riscos e evidências num workspace controlado para equipas B2B europeias.',
  },
  'ai-risk-assessment': {
    key: 'ai-risk-assessment',
    slug: 'avaliacao-de-risco-de-ia',
    navLabel: 'Avaliação de risco de IA',
    title: 'Software de Avaliação de Risco de IA e Workflows de Revisão',
    description: 'Registe sinais de risco, contexto de avaliação, decisões, responsáveis e ações com workflows rastreáveis para equipas B2B europeias.',
    eyebrow: 'Avaliação de risco de IA',
    intro: 'Transforme a análise de risco num processo operacional repetível. Recolha contexto, envolva as pessoas certas e mantenha decisões ligadas aos sistemas e evidências correspondentes.',
    problemTitle: 'Decisões de risco precisam de contexto, responsabilidade e histórico',
    problem: 'Uma etiqueta de risco, por si só, não é suficiente. As equipas precisam de compreender o caso de uso, pessoas afetadas, dados, nível de automação, dependências de fornecedores e controlos que suportam cada conclusão.',
    capabilitiesTitle: 'Estruture todo o contexto da revisão',
    capabilities: [
      'Sinais de risco relacionados com uso, impacto, dados, utilizadores e implementação',
      'Classificação inicial, estado de revisão e justificação documentada',
      'Responsáveis, tarefas de mitigação e pontos de aprovação',
      'Evidências, políticas, fornecedores e histórico de atividade ligados à avaliação',
    ],
    workflowTitle: 'Da recolha inicial à decisão revista',
    workflow: ['Recolher contexto do sistema e do caso de uso', 'Registar sinais de risco relevantes', 'Atribuir revisores e pedidos de evidência', 'Documentar conclusões, ações e necessidades de monitorização'],
    faqTitle: 'Perguntas sobre avaliação de risco de IA',
    faq: [
      { question: 'Esta ferramenta faz classificação jurídica automática?', answer: 'Não. A RISCK COMPLY apoia workflows estruturados de readiness e risco. Não substitui avaliação jurídica qualificada nem garante uma classificação regulatória.' },
      { question: 'As avaliações podem ser revistas?', answer: 'Sim. Devem ser revistas quando mudam o sistema, caso de uso, fornecedor, dados ou contexto jurídico.' },
      { question: 'Quem deve participar na avaliação?', answer: 'Consoante o caso, podem participar produto, engenharia, segurança, privacidade, jurídico, compliance, procurement e o responsável de negócio.' },
    ],
    ctaTitle: 'Torne a avaliação de risco repetível e preparada para revisão',
    ctaText: 'Reúna contexto, decisões, responsáveis e evidências de suporte em vez de os gerir em documentos desligados.',
  },
  'evidence-management': {
    key: 'evidence-management',
    slug: 'gestao-de-evidencias',
    navLabel: 'Gestão de evidências',
    title: 'Software de Gestão de Evidências para Compliance de IA',
    description: 'Organize evidências de governança de IA, documentos, decisões, responsáveis e estado de revisão em packs estruturados.',
    eyebrow: 'Gestão de evidências de compliance',
    intro: 'Prepare evidências como disciplina operacional, não como uma procura de documentos à última hora. A RISCK COMPLY liga registos, decisões e ficheiros aos sistemas e controlos que suportam.',
    problemTitle: 'A evidência perde valor quando ninguém sabe o que demonstra',
    problem: 'Ficheiros guardados em pastas genéricas raramente mostram a que sistema, controlo, decisão ou responsável estão ligados. A gestão estruturada preserva contexto e acelera a revisão.',
    capabilitiesTitle: 'Construa packs de evidência com contexto claro',
    capabilities: [
      'Ligar documentos e registos a sistemas, avaliações e controlos',
      'Acompanhar responsáveis, estado de revisão, datas e itens em falta',
      'Registar decisões e justificação juntamente com anexos',
      'Preparar packs delimitados para jurídico, segurança, procurement ou auditoria',
    ],
    workflowTitle: 'Do pedido de evidência ao pack preparado para revisão',
    workflow: ['Definir o requisito de evidência', 'Atribuir responsável e prazo', 'Anexar ou preparar o registo de suporte', 'Rever completude e preservar o histórico de atividade'],
    faqTitle: 'Perguntas sobre gestão de evidências',
    faq: [
      { question: 'O que pode integrar um pack de evidência de governança de IA?', answer: 'Depende do sistema e do âmbito, mas pode incluir inventário, avaliações, políticas, aprovações, informação de fornecedores, testes e evidências de monitorização.' },
      { question: 'Guardar um documento prova que o controlo é eficaz?', answer: 'Não. A evidência precisa de ser relevante, atual e ligada ao controlo ou decisão que pretende suportar.' },
      { question: 'As evidências podem ser organizadas por sistema de IA?', answer: 'Sim. A plataforma foi concebida para ligar evidências a sistemas, revisões, responsáveis e atividades de governança no âmbito da organização.' },
    ],
    ctaTitle: 'Transforme ficheiros dispersos em evidência de governança preparada para revisão',
    ctaText: 'Organize evidências por sistema, responsável, requisito e estado para saber o que existe e o que ainda falta.',
  },
  'ai-governance-workflows': {
    key: 'ai-governance-workflows',
    slug: 'workflows-de-governanca-de-ia',
    navLabel: 'Workflows de governança',
    title: 'Software de Workflows de Governança de IA para Equipas Multidisciplinares',
    description: 'Coordene intake, responsáveis, avaliações, aprovações, evidências e monitorização entre produto, jurídico, segurança, privacidade e compliance.',
    eyebrow: 'Workflows de governança de IA',
    intro: 'Dê a cada sistema de IA um percurso claro desde a descoberta até à revisão contínua. Coordene responsabilidades sem transformar governança numa cadeia de folhas de cálculo e emails.',
    problemTitle: 'A governança bloqueia quando o trabalho não tem responsável nem próximo passo',
    problem: 'A governança de IA é multidisciplinar. Sem responsabilidades, estado de revisão e escalamento visíveis, o trabalho pode ficar por concluir mesmo quando existem políticas.',
    capabilitiesTitle: 'Coordene o trabalho de governança num único local',
    capabilities: [
      'Intake estruturado e atribuição de responsabilidade',
      'Etapas de revisão, tarefas, prazos e aprovações',
      'Pedidos de evidência ligados a sistemas e avaliações',
      'Monitorização, revisão de alterações e histórico rastreável',
    ],
    workflowTitle: 'Um fluxo operacional partilhado',
    workflow: ['Descobrir e registar o caso de uso de IA', 'Atribuir responsáveis e revisores', 'Avaliar risco e recolher evidências', 'Aprovar, documentar e monitorizar alterações'],
    faqTitle: 'Perguntas sobre workflows de governança',
    faq: [
      { question: 'Que equipas podem participar?', answer: 'É comum envolver produto, engenharia, jurídico, compliance, privacidade, segurança, procurement e responsáveis de negócio.' },
      { question: 'O workflow substitui políticas internas?', answer: 'Não. O workflow ajuda a executar e evidenciar processos; políticas e requisitos jurídicos continuam a precisar de responsáveis e revisão adequada.' },
      { question: 'Porque ligar tarefas aos sistemas de IA?', answer: 'A ligação preserva contexto, reduz ambiguidade e torna mais claro porque existe uma ação e quem é responsável.' },
    ],
    ctaTitle: 'Opere governança de IA como um processo real de negócio',
    ctaText: 'Crie responsabilidade visível, etapas consistentes e acompanhamento rastreável para cada sistema de IA.',
  },
  'vendor-ai-risk': {
    key: 'vendor-ai-risk',
    slug: 'risco-de-fornecedores-de-ia',
    navLabel: 'Risco de fornecedores de IA',
    title: 'Workflows de Risco de Fornecedores de IA e Assurance de Terceiros',
    description: 'Acompanhe fornecedores de IA, serviços, contratos, contexto de dados, pedidos de evidência e decisões de procurement e third-party risk.',
    eyebrow: 'Risco de fornecedores de IA',
    intro: 'Compreenda que fornecedores suportam cada caso de uso de IA e que evidências estão disponíveis antes de decisões de compra, implementação ou renovação.',
    problemTitle: 'O risco do fornecedor não pode ser avaliado sem o contexto de utilização',
    problem: 'O mesmo serviço de IA pode criar riscos diferentes consoante os dados, utilizadores, integrações e processo de negócio. A revisão precisa de evidência do fornecedor e contexto do sistema.',
    capabilitiesTitle: 'Ligue a revisão do fornecedor à utilização operacional',
    capabilities: [
      'Perfil do fornecedor, serviços, regiões e sistemas de IA ligados',
      'Pedidos de evidência de segurança, privacidade, contrato e governança',
      'Responsáveis, findings, decisões e ações de mitigação',
      'Contexto para renovação, alterações materiais e dependências',
    ],
    workflowTitle: 'Uma revisão estruturada do fornecedor',
    workflow: ['Registar fornecedor e caso de uso ligado', 'Pedir evidências de assurance relevantes', 'Rever findings com stakeholders responsáveis', 'Documentar decisões, condições e ações'],
    faqTitle: 'Perguntas sobre risco de fornecedores de IA',
    faq: [
      { question: 'A revisão do fornecedor é igual à avaliação do sistema?', answer: 'Não. A assurance avalia o terceiro e o serviço; a avaliação do sistema considera o caso de uso, impacto e controlos da organização. Devem estar ligadas.' },
      { question: 'Que evidências podem ser pedidas ao fornecedor?', answer: 'Podem incluir documentação de segurança, termos de tratamento de dados, informação sobre o serviço ou modelo, processo de incidentes e compromissos contratuais.' },
      { question: 'Um fornecedor pode estar ligado a vários sistemas?', answer: 'Sim. Um fornecedor pode suportar vários sistemas ou processos, cada um com responsáveis e contexto de risco distintos.' },
    ],
    ctaTitle: 'Torne a revisão de fornecedores de IA mais simples de operar',
    ctaText: 'Ligue fornecedores, sistemas, pedidos de evidência e decisões para que procurement e governança partilhem o mesmo contexto.',
  },
  'eu-ai-act-readiness': {
    key: 'eu-ai-act-readiness',
    slug: 'preparacao-para-o-ai-act',
    navLabel: 'Preparação para o AI Act',
    title: 'Plataforma de Preparação para o EU AI Act para Equipas B2B Europeias',
    description: 'Organize sistemas de IA, responsabilidades, contexto de risco, documentação e evidências para apoiar trabalho prático de preparação para o EU AI Act.',
    eyebrow: 'Preparação para o EU AI Act',
    intro: 'Construa os registos operacionais necessários para compreender a utilização de IA, coordenar responsabilidades e preparar evidências para revisão jurídica e de compliance.',
    problemTitle: 'Preparação exige mais do que uma checklist pontual',
    problem: 'Sistemas, fornecedores, casos de uso e interpretações jurídicas mudam. As equipas precisam de um modelo operacional que mantenha inventário, decisões, evidências e ações ligados ao longo do tempo.',
    capabilitiesTitle: 'Apoie readiness ao longo do ciclo de governança',
    capabilities: [
      'Inventário de IA e atribuição de responsabilidades',
      'Sinais de risco, avaliações e justificação de revisão',
      'Políticas, packs de evidência e documentação de fornecedores',
      'Tarefas, aprovações, monitorização e histórico de atividade',
    ],
    workflowTitle: 'Da visibilidade à preparação de evidências',
    workflow: ['Identificar sistemas e papéis organizacionais', 'Avaliar casos de uso e obrigações relevantes', 'Preparar documentação e evidências de suporte', 'Rever alterações, lacunas e ações contínuas'],
    faqTitle: 'Perguntas sobre preparação para o EU AI Act',
    faq: [
      { question: 'A RISCK COMPLY presta aconselhamento jurídico?', answer: 'Não. A plataforma apoia operações de governança e preparação de evidências. A organização deve obter aconselhamento jurídico qualificado para as suas obrigações específicas.' },
      { question: 'Usar a plataforma torna uma empresa compliant?', answer: 'Não. Nenhum software garante resultados de conformidade. A readiness depende da organização, sistemas, controlos, evidências, decisões e interpretação aplicável.' },
      { question: 'Que equipas europeias podem utilizar a plataforma?', answer: 'Foi concebida para equipas B2B multidisciplinares de governança de IA, incluindo compliance, jurídico, segurança, privacidade, produto, engenharia e procurement.' },
    ],
    ctaTitle: 'Construa uma base operacional para preparação para o AI Act',
    ctaText: 'Organize sistemas, responsáveis, riscos, documentos e evidências para rever claramente o trabalho de governança de IA.',
  },
  'audit-trails': {
    key: 'audit-trails',
    slug: 'trilhos-de-auditoria-de-ia',
    navLabel: 'Trilhos de auditoria',
    title: 'Trilhos de Auditoria e Histórico de Atividade de Governança de IA',
    description: 'Mantenha ações, alterações, decisões e evidências de governança de IA rastreáveis para revisão interna, investigação e procurement.',
    eyebrow: 'Histórico de atividade de governança',
    intro: 'Preserve o contexto por detrás da atividade de governança. Reveja quem alterou registos, que decisão foi tomada e que evidências suportaram o trabalho.',
    problemTitle: 'Um documento final raramente explica como se chegou à decisão',
    problem: 'Os revisores podem precisar da sequência de ações, alterações de responsabilidade, aprovações e atualizações de evidência. Um histórico rastreável ajuda a reconstruir esse contexto.',
    capabilitiesTitle: 'Mantenha a atividade de governança preparada para revisão',
    capabilities: [
      'Histórico de sistemas, avaliações e evidências',
      'Atividade de responsáveis, tarefas e aprovações',
      'Contexto de eventos relevantes para segurança e compliance',
      'Registos delimitados para apoio a revisão e investigação',
    ],
    workflowTitle: 'Utilize o histórico durante uma revisão',
    workflow: ['Identificar o sistema ou registo', 'Rever eventos e utilizadores responsáveis', 'Ligar alterações a decisões e evidências', 'Registar ações de acompanhamento ou correção'],
    faqTitle: 'Perguntas sobre trilhos de auditoria',
    faq: [
      { question: 'Os registos são juridicamente imutáveis?', answer: 'A RISCK COMPLY não afirma imutabilidade externa sem evidência técnica separada. O histórico é concebido para rastreabilidade e revisão.' },
      { question: 'Porque são úteis para governança?', answer: 'Ajudam a compreender alterações, responsabilidades e decisões, apoiando revisão interna, análise de incidentes e diligência de procurement.' },
      { question: 'Substituem evidência formal de auditoria?', answer: 'Não. Podem apoiar um pack de evidência, mas a prova necessária depende do âmbito e do revisor.' },
    ],
    ctaTitle: 'Mantenha decisões de governança de IA rastreáveis',
    ctaText: 'Preserve contexto de atividade entre sistemas, avaliações, evidências e ações de acompanhamento.',
  },
  'compliance-documentation': {
    key: 'compliance-documentation',
    slug: 'documentacao-de-compliance-de-ia',
    navLabel: 'Documentação de compliance',
    title: 'Software de Documentação de Governança e Compliance de IA',
    description: 'Prepare, organize e mantenha políticas, registos, relatórios e documentação de governança de IA com responsáveis e estado de revisão claros.',
    eyebrow: 'Documentação de compliance de IA',
    intro: 'Crie documentação ligada aos sistemas, decisões e evidências que descreve. Mantenha responsáveis e datas de revisão visíveis à medida que o trabalho evolui.',
    problemTitle: 'A documentação fica desatualizada quando está separada das operações',
    problem: 'Políticas e relatórios são mais fáceis de manter quando estão ligados a sistemas, avaliações, responsáveis e evidências atuais, em vez de serem copiados entre ficheiros isolados.',
    capabilitiesTitle: 'Mantenha documentação de governança com contexto',
    capabilities: [
      'Políticas, relatórios, registos e resumos preparados para revisão',
      'Responsável, estado, versão e datas de revisão',
      'Ligações a sistemas, avaliações, evidências e decisões',
      'Preparação controlada para revisão interna, jurídica ou de procurement',
    ],
    workflowTitle: 'Um processo de documentação sustentável',
    workflow: ['Selecionar finalidade e âmbito do documento', 'Ligar sistemas, responsáveis e evidências', 'Preparar e rever conteúdo', 'Aprovar, publicar e agendar revisão futura'],
    faqTitle: 'Perguntas sobre documentação',
    faq: [
      { question: 'Documentos gerados substituem revisão jurídica?', answer: 'Não. Materiais gerados ou baseados em templates devem ser revistos pelos responsáveis jurídicos, de compliance e especialistas adequados.' },
      { question: 'Porque ligar documentos a sistemas?', answer: 'A ligação clarifica o âmbito e ajuda a atualizar documentação quando muda o sistema, caso de uso, fornecedor ou avaliação.' },
      { question: 'Que documentos podem ser organizados?', answer: 'Exemplos incluem políticas de IA, inventários, resumos de avaliação, relatórios de governança, registos de fornecedores e documentação de packs de evidência.' },
    ],
    ctaTitle: 'Mantenha documentação de governança ligada ao trabalho real',
    ctaText: 'Prepare e mantenha documentos com responsabilidade, evidências de suporte e estado de revisão visíveis.',
  },
};
